import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { CheckCircle2, FileCheck2, Loader2, XCircle } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { advancePurchaseRequest, listPendingApprovals, rejectPurchaseRequest } from './api';

const field = 'w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';
const stages = ['PREPARED', 'CHECKED', 'PREAPPROVED', 'APPROVED'];

function Body() {
  const [rows, setRows] = useState<any[]>([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRows(await listPendingApprovals()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load approvals.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const total = useMemo(() => rows.reduce((sum, row) => sum + (row.lines ?? []).reduce((value: number, line: any) => value + Number(line.quantity || 0) * Number(line.rate || 0), 0), 0), [rows]);
  async function run(key: string, action: () => Promise<unknown>, message: string) { setBusy(key); setError(''); setNotice(''); try { await action(); setNotice(message); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Approval action failed.'); } finally { setBusy(''); } }
  function approve(e: FormEvent<HTMLFormElement>, row: any) { e.preventDefault(); const values = new FormData(e.currentTarget); void run(row.purchase_request_id, () => advancePurchaseRequest(row.purchase_request_id, String(values.get('name')), String(values.get('notes') || '')), 'Approval stage recorded.'); }
  function reject(e: FormEvent<HTMLFormElement>, row: any) { e.preventDefault(); const values = new FormData(e.currentTarget); void run(row.purchase_request_id, () => rejectPurchaseRequest(row.purchase_request_id, String(values.get('reason'))), 'Purchase request rejected.'); }
  return <div className="space-y-5">
    <div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Controlled workflow</p><h1 className="text-2xl font-bold mt-1">Approval Inbox</h1><p className="text-sm text-slate-500 mt-1">Review pending purchase requests and record accountable approval decisions.</p></div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice && <div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4" />{notice}</div>}
    <div className="grid sm:grid-cols-3 gap-3">{[['Pending requests', rows.length], ['Pending value', total.toLocaleString(undefined, { maximumFractionDigits: 2 })], ['Oldest', rows[0]?.request_date ?? '—']].map(([label, value]) => <div key={label} className="bg-white border rounded-2xl p-4"><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>)}</div>
    {loading ? <div className="p-24 flex justify-center"><Loader2 className="animate-spin text-brand-600" /></div> : !rows.length ? <div className="bg-white border rounded-2xl p-16 text-center text-slate-400"><FileCheck2 className="mx-auto mb-3 w-8 h-8" /><p className="font-semibold">Approval inbox is clear.</p></div> : rows.map(row => <article key={row.purchase_request_id} className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2 items-center"><b className="font-mono text-sm">{row.purchase_request_no}</b><span className="rounded-full bg-amber-50 text-amber-700 px-2 py-1 text-[10px] font-bold">{row.status.replaceAll('_', ' ')}</span></div><h2 className="font-bold mt-2">{row.purpose}</h2><p className="text-xs text-slate-500 mt-1">{row.department} · Requested by {row.requested_by} · {row.request_date}</p></div><RecordActions printTitle={`Purchase Request ${row.purchase_request_no}`} printRecord={{ request_no: row.purchase_request_no, date: row.request_date, requested_by: row.requested_by, department: row.department, purpose: row.purpose, remarks: row.remarks, status: row.status, approval_chain: row.approvals, items: row.lines, estimated_total: (row.lines ?? []).reduce((sum: number, line: any) => sum + Number(line.quantity || 0) * Number(line.rate || 0), 0) }} disabledReason="Approval decisions must use the controlled approve or reject actions." /></div>
      <div className="p-5 grid xl:grid-cols-[1.4fr_1fr] gap-5"><div><div className="grid grid-cols-4 gap-2 mb-4">{stages.map((stage, index) => { const approval = row.approvals?.find((item: any) => item.approval_level === stage); return <div key={stage} className={`rounded-xl p-2 border ${approval ? 'bg-emerald-50 border-emerald-100' : 'bg-slate-50'}`}><p className="text-[9px] font-bold">{index + 1}. {stage}</p><p className="text-xs mt-1 truncate">{approval?.approver_name ?? 'Pending'}</p></div>; })}</div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-left"><tr><th className="p-2">Item</th><th className="p-2">Qty</th><th className="p-2">Rate</th><th className="p-2">Amount</th></tr></thead><tbody>{row.lines?.map((line: any, index: number) => <tr key={index} className="border-t"><td className="p-2">{line.item_description}</td><td className="p-2">{Number(line.quantity).toLocaleString()} {line.uom_text}</td><td className="p-2">{line.rate == null ? '—' : Number(line.rate).toLocaleString()}</td><td className="p-2 font-bold">{line.rate == null ? '—' : (Number(line.quantity) * Number(line.rate)).toLocaleString()}</td></tr>)}</tbody></table></div></div>
        <div className="space-y-3 print:hidden"><form onSubmit={e => approve(e, row)} className="rounded-xl bg-emerald-50 p-3 space-y-2"><p className="text-xs font-bold text-emerald-800">Approve next stage</p><input required name="name" placeholder="Approver name" className={field} /><input name="notes" placeholder="Approval notes" className={field} /><button disabled={!!busy} className="w-full rounded-xl bg-emerald-600 text-white py-2.5 text-sm font-bold flex justify-center gap-2">{busy === row.purchase_request_id ? <Loader2 className="w-4 h-4 animate-spin" /> : <CheckCircle2 className="w-4 h-4" />}Approve</button></form><form onSubmit={e => reject(e, row)} className="rounded-xl bg-red-50 p-3 space-y-2"><p className="text-xs font-bold text-red-800">Reject request</p><input required name="reason" placeholder="Mandatory rejection reason" className={field} /><button disabled={!!busy} className="w-full rounded-xl border border-red-200 bg-white text-red-700 py-2.5 text-sm font-bold flex justify-center gap-2"><XCircle className="w-4 h-4" />Reject</button></form></div>
      </div></article>)}
  </div>;
}

export default function ApprovalInbox() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
