import{useCallback,useEffect,useMemo,useState,type FormEvent}from'react';
import{ArrowRightLeft,CheckCircle2,Loader2,Plus,Trash2}from'lucide-react';
import FactoryGuard from'./FactoryGuard';import FactoryShell from'./FactoryShell';import{listCustomerCustodyData,postCustomerCustody}from'./api';
const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';
type Line={item_kind:'material'|'product';item_id:string;uom_id:string;location_id:string;movement_type:string;quantity:string;ownership:string;remarks:string};
const blank=(movement_type='TRANSFER_OUT'):Line=>({item_kind:'material',item_id:'',uom_id:'',location_id:'',movement_type,quantity:'',ownership:'CUSTOMER_OWNED',remarks:''});
const patterns:Record<string,string[]>= {CUSTOMER_MATERIAL_RECEIPT:['RECEIPT'],OUTSOURCE_ISSUE:['TRANSFER_OUT','TRANSFER_IN'],OUTSOURCE_RETURN:['TRANSFER_OUT','TRANSFER_IN'],PRODUCTION_ISSUE:['TRANSFER_OUT','TRANSFER_IN'],PRODUCTION_RECONCILIATION:['CONSUMPTION','WASTE','PRODUCTION_RECEIPT'],CUSTOMER_DISPATCH:['DISPATCH']};
function Body(){const[data,setData]=useState<any>({customers:[],materials:[],products:[],uoms:[],locations:[],documents:[]}),[type,setType]=useState('CUSTOMER_MATERIAL_RECEIPT'),[lines,setLines]=useState<Line[]>(patterns.CUSTOMER_MATERIAL_RECEIPT.map(blank)),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{setData(await listCustomerCustodyData())}catch(e){setError(e instanceof Error?e.message:'Could not load customer custody.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 function changeType(v:string){setType(v);setLines(patterns[v].map(blank))}function change(i:number,k:keyof Line,v:string){setLines(x=>x.map((r,n)=>n===i?{...r,[k]:v}:r))}
 const help=useMemo(()=>type==='CUSTOMER_MATERIAL_RECEIPT'?'Receive customer-owned raw material into our custody without creating a purchase.':type==='OUTSOURCE_ISSUE'?'Move identical material from our store to the dyer/printer location. Both lines must match.':type==='OUTSOURCE_RETURN'?'Move identical processed material from the outsourcer back to our store.':type==='PRODUCTION_ISSUE'?'Transfer customer material from store to the production floor; consumption is recorded later during reconciliation.':type==='PRODUCTION_RECONCILIATION'?'Record actual material consumed, waste, and fabric received in one document.':'Issue finished fabric from our custody and dispatch it to the customer.',[type]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);setBusy(true);setError('');setNotice('');try{await postCustomerCustody({type,customer:String(d.get('customer')),reference:String(d.get('reference')),party:String(d.get('party')||''),remarks:String(d.get('remarks')||''),lines:lines.map(x=>({material_id:x.item_kind==='material'?x.item_id:null,product_id:x.item_kind==='product'?x.item_id:null,uom_id:x.uom_id,location_id:x.location_id,movement_type:x.movement_type,quantity:Number(x.quantity),ownership:x.ownership,remarks:x.remarks}))});f.reset();setLines(patterns[type].map(blank));setNotice('Customer custody ledger posted.');await load()}catch(x){setError(x instanceof Error?x.message:'Could not post custody movement.')}finally{setBusy(false)}}
 return <div className="space-y-5"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Customer material conversion</p><h1 className="text-2xl font-bold mt-1">Customer material custody</h1><p className="text-sm text-slate-500 mt-1">One ledger from receipt through outsourcing, production, and customer dispatch.</p></div>{error&&<div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice&&<div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4"/>{notice}</div>}
<form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4"><div className="flex items-center gap-2"><ArrowRightLeft className="text-brand-600"/><h2 className="font-bold">Post custody document</h2></div><div className="grid md:grid-cols-4 gap-3"><select value={type} onChange={e=>changeType(e.target.value)} className={field}><option value="CUSTOMER_MATERIAL_RECEIPT">Customer material receipt</option><option value="OUTSOURCE_ISSUE">Issue to outsourcer</option><option value="OUTSOURCE_RETURN">Return from outsourcer</option><option value="PRODUCTION_ISSUE">Issue to production</option><option value="PRODUCTION_RECONCILIATION">Production receipt & consumption</option><option value="CUSTOMER_DISPATCH">Dispatch to customer</option></select><select required name="customer" className={field}><option value="">Customer…</option>{data.customers.map((x:any)=><option key={x.customer_id} value={x.customer_id}>{x.customer_code} · {x.customer_name}</option>)}</select><input required name="reference" placeholder="Reference / challan / batch" className={field}/><input name="party" placeholder={['OUTSOURCE_ISSUE','OUTSOURCE_RETURN','PRODUCTION_ISSUE'].includes(type)?'Dyer / printer':'Handled by'} className={field}/></div><p className="rounded-xl bg-blue-50 p-3 text-xs text-blue-800">{help}</p>
 <div className="space-y-2">{lines.map((x,i)=>{const items=x.item_kind==='material'?data.materials:data.products;return <div key={i} className="grid xl:grid-cols-8 md:grid-cols-4 gap-2 bg-slate-50 p-3 rounded-xl"><select value={x.movement_type} onChange={e=>change(i,'movement_type',e.target.value)} className={field}>{patterns[type].map(v=><option key={v}>{v}</option>)}</select><select value={x.item_kind} onChange={e=>{change(i,'item_kind',e.target.value as Line['item_kind']);change(i,'item_id','')}} className={field}><option value="material">Material</option><option value="product">Finished fabric</option></select><select required value={x.item_id} onChange={e=>change(i,'item_id',e.target.value)} className={field}><option value="">Item…</option>{items.map((m:any)=><option key={m.material_id??m.product_id} value={m.material_id??m.product_id}>{m.material_code??m.product_code} · {m.material_name??m.description}</option>)}</select><select required value={x.location_id} onChange={e=>change(i,'location_id',e.target.value)} className={field}><option value="">Location / status…</option>{data.locations.map((l:any)=><option key={l.location_id} value={l.location_id}>{l.location_name}</option>)}</select><input required type="number" min=".001" step=".001" value={x.quantity} onChange={e=>change(i,'quantity',e.target.value)} placeholder="Quantity" className={field}/><select required value={x.uom_id} onChange={e=>change(i,'uom_id',e.target.value)} className={field}><option value="">UOM…</option>{data.uoms.map((u:any)=><option key={u.uom_id} value={u.uom_id}>{u.uom_code}</option>)}</select><select value={x.ownership} onChange={e=>change(i,'ownership',e.target.value)} className={field}><option value="CUSTOMER_OWNED">Customer owned</option><option value="TOLL_MANUFACTURING">Toll manufacturing</option></select><div className="flex gap-1"><input value={x.remarks} onChange={e=>change(i,'remarks',e.target.value)} placeholder="Remarks" className={field}/><button type="button" disabled={lines.length===1||['OUTSOURCE_ISSUE','OUTSOURCE_RETURN','PRODUCTION_ISSUE'].includes(type)} onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))} className="px-2 text-red-500 disabled:opacity-30"><Trash2 className="w-4 h-4"/></button></div></div>})}</div>
 <div className="flex justify-between"><button type="button" disabled={['OUTSOURCE_ISSUE','OUTSOURCE_RETURN','PRODUCTION_ISSUE'].includes(type)} onClick={()=>setLines(v=>[...v,blank(patterns[type][0])])} className="px-4 py-2.5 rounded-xl border text-sm font-bold disabled:opacity-40"><Plus className="w-4 h-4 inline mr-1"/>Add line</button><div className="flex gap-2"><input name="remarks" placeholder="Document remarks" className={field}/><button disabled={busy} className="px-5 py-2.5 rounded-xl bg-brand-600 text-white text-sm font-bold disabled:opacity-40">{busy?<Loader2 className="w-4 h-4 animate-spin"/>:'Post document'}</button></div></div></form>
 <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Recent custody documents</h2>{loading?<div className="p-12 flex justify-center"><Loader2 className="animate-spin"/></div>:!data.documents.length?<p className="p-12 text-center text-slate-400">No custody documents posted.</p>:<div className="divide-y">{data.documents.map((d:any)=><div key={d.custody_document_id} className="p-4 grid md:grid-cols-4 gap-2 text-sm"><b className="font-mono">{d.document_no}</b><span>{d.customer?.customer_name}</span><span>{d.transaction_type.replaceAll('_',' ')}</span><span className="md:text-right">{d.reference}</span></div>)}</div>}</section></div>}
export default function CustomerCustody(){return <FactoryGuard><FactoryShell><Body/></FactoryShell></FactoryGuard>}
