import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { CheckCircle2, ClipboardList, Loader2, Plus, Search } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { createFactoryOrder, listCustomerOrders, listSetupData } from './api';

const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';
function Body(){
  const[orders,setOrders]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]);
  const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[orderRows,setup]=await Promise.all([listCustomerOrders(),listSetupData()]);setOrders(orderRows);setCustomers(setup.customers);setProducts(setup.products)}catch(e){setError(e instanceof Error?e.message:'Could not load orders.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const filtered=useMemo(()=>orders.filter(o=>!query||JSON.stringify(o).toLowerCase().includes(query.toLowerCase())),[orders,query]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);setError('');setNotice('');try{await createFactoryOrder({customerId:String(d.get('customer')),productId:String(d.get('product')),quantity:Number(d.get('quantity')),notes:String(d.get('notes')||'')});form.reset();setNotice('Confirmed order and production order created.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not create order.')}finally{setBusy(false)}}
  return <div className="space-y-5"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Customers / Sales</p><h1 className="text-2xl font-bold mt-1">Order Booking</h1><p className="text-sm text-slate-500 mt-1">Book confirmed customer demand and send it directly into production planning.</p></div>
  {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}{notice&&<div className="p-3 rounded-xl bg-emerald-50 text-emerald-700 text-sm flex gap-2"><CheckCircle2 className="w-4 h-4"/>{notice}</div>}
  <section className="bg-white border rounded-2xl p-5 print:hidden"><h2 className="font-bold mb-4">New confirmed order</h2><form onSubmit={submit} className="grid md:grid-cols-2 xl:grid-cols-5 gap-3"><select required name="customer" className={field}><option value="">Customer…</option>{customers.map(x=><option key={x.customer_id} value={x.customer_id}>{x.customer_code} · {x.customer_name}</option>)}</select><select required name="product" className={field}><option value="">Product…</option>{products.map(x=><option key={x.product_id} value={x.product_id}>{x.product_code} · {x.description}</option>)}</select><input required name="quantity" type="number" min=".01" step=".01" placeholder="Quantity (meters)" className={field}/><input name="notes" placeholder="Customer PO / instructions" className={field}/><button disabled={busy||!customers.length||!products.length} className="rounded-xl bg-brand-600 text-white px-4 py-2.5 text-sm font-bold flex items-center justify-center gap-2 disabled:opacity-40">{busy?<Loader2 className="w-4 h-4 animate-spin"/>:<Plus className="w-4 h-4"/>}Book order</button></form></section>
  <section className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between"><div><h2 className="font-bold">Order register</h2><p className="text-xs text-slate-500">{filtered.length} orders</p></div><label className="relative print:hidden"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search orders…" className="border rounded-xl py-2 pl-9 pr-3 text-sm"/></label></div>{loading?<div className="py-20 flex justify-center"><Loader2 className="animate-spin"/></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Order</th><th className="p-3">Customer</th><th className="p-3">Product</th><th className="p-3">Quantity</th><th className="p-3">Production order</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{filtered.map(o=>{const item=o.items?.[0],production=item?.production?.[0];return <tr key={o.order_id} className="border-t"><td className="p-3"><b className="font-mono text-xs">{o.order_no}</b><p className="text-xs text-slate-500">{o.order_date}</p></td><td className="p-3">{o.customer?.customer_name}</td><td className="p-3"><b>{item?.product?.product_code}</b><p className="text-xs text-slate-500">{item?.product?.description}</p></td><td className="p-3 font-semibold">{Number(item?.quantity||0).toLocaleString()} {item?.uom?.uom_code}</td><td className="p-3 font-mono text-xs">{production?.production_order_no??'—'}</td><td className="p-3"><span className="px-2 py-1 rounded-full bg-brand-50 text-brand-700 text-[10px] font-bold">{production?.status??o.status}</span></td><td className="p-3"><RecordActions printTitle={`Customer Order ${o.order_no}`} printRecord={{order_no:o.order_no,order_date:o.order_date,customer:o.customer?.customer_name,product_code:item?.product?.product_code,description:item?.product?.description,quantity:item?.quantity,uom:item?.uom?.uom_code,production_order:production?.production_order_no,status:production?.status??o.status,notes:o.notes}} disabledReason="Confirmed orders require an audited cancellation rather than deletion."/></td></tr>})}</tbody></table>{!filtered.length&&<div className="py-16 text-center text-slate-400"><ClipboardList className="mx-auto mb-2"/>No orders found.</div>}</div>}</section></div>
}
export default function CustomerOrders(){return <FactoryGuard><FactoryShell><Body/></FactoryShell></FactoryGuard>}
