import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { CalendarDays, CheckCircle2, Loader2, Truck } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { listDispatchScheduleData, scheduleDispatch } from './api';

const field = 'w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';
const today = () => new Date().toISOString().slice(0, 10);

function Body() {
  const [data, setData] = useState<any>({ goods: [], schedules: [] }), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setData(await listDispatchScheduleData()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load dispatch schedule.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const stats = useMemo(() => ({ planned: data.schedules.filter((row: any) => row.status === 'PLANNED').length, today: data.schedules.filter((row: any) => row.scheduled_date === today() && row.status !== 'CANCELLED').length, ready: data.goods.length }), [data]);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); setBusy(true); setError(''); setNotice('');
    try { await scheduleDispatch({ p_finished_goods: values.get('goods'), p_date: values.get('date'), p_location: values.get('location'), p_vehicle: values.get('vehicle') || null, p_driver: values.get('driver') || null, p_remarks: values.get('remarks') || null }); form.reset(); setNotice('Finished goods scheduled for dispatch.'); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not schedule dispatch.'); } finally { setBusy(false); }
  }
  return <div className="space-y-5">
    <div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Packing & dispatch</p><h1 className="text-2xl font-bold mt-1">Dispatch Schedule</h1><p className="text-sm text-slate-500 mt-1">Plan available finished goods for customer delivery.</p></div>
    <div className="grid grid-cols-3 gap-3">{[['Available lots', stats.ready], ['Planned', stats.planned], ['Due today', stats.today]].map(item => <div key={String(item[0])} className="bg-white border rounded-2xl p-4"><p className="text-xs font-bold text-slate-500">{item[0]}</p><p className="text-2xl font-bold mt-2">{item[1]}</p></div>)}</div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice && <div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4" />{notice}</div>}
    <form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4 print:hidden"><div className="flex gap-2"><CalendarDays className="text-brand-600" /><h2 className="font-bold">Schedule delivery</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3"><select required name="goods" className={field}><option value="">Finished goods lot…</option>{data.goods.map((row: any) => <option key={row.finished_goods_id} value={row.finished_goods_id}>{row.product?.product_code} · {row.batch?.batch_code} · {row.batch?.order?.order_item?.order?.customer?.customer_name} · {Number(row.quantity).toLocaleString()} {row.uom?.uom_code}</option>)}</select><input required name="date" type="date" min={today()} className={field} /><input required name="location" placeholder="Delivery location" className={field} /><input name="vehicle" placeholder="Vehicle number" className={field} /><input name="driver" placeholder="Driver name" className={field} /><input name="remarks" placeholder="Delivery remarks" className={field} /></div><button disabled={busy || !data.goods.length} className="px-5 py-2.5 rounded-xl bg-brand-600 text-white text-sm font-bold disabled:opacity-40">{busy ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Schedule dispatch'}</button></form>
    <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Delivery plan</h2>{loading ? <div className="p-16 flex justify-center"><Loader2 className="animate-spin" /></div> : !data.schedules.length ? <p className="p-12 text-center text-slate-400">No deliveries scheduled.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{['Schedule', 'Date', 'Customer', 'Finished goods', 'Quantity', 'Delivery', 'Status', 'Actions'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{data.schedules.map((row: any) => <tr key={row.dispatch_schedule_id} className="border-t"><td className="p-3 font-mono text-xs font-bold">{row.schedule_no}</td><td className="p-3">{row.scheduled_date}</td><td className="p-3">{row.customer?.customer_name}</td><td className="p-3"><b>{row.goods?.product?.product_code}</b><p className="text-xs text-slate-500">{row.goods?.product?.description} · {row.goods?.batch?.batch_code}</p></td><td className="p-3 font-mono">{Number(row.quantity).toLocaleString()} {row.uom?.uom_code}</td><td className="p-3"><p>{row.delivery_location}</p><p className="text-xs text-slate-500 flex gap-1"><Truck className="w-3 h-3" />{row.vehicle_no ?? 'Vehicle pending'} · {row.driver_name ?? 'Driver pending'}</p></td><td className="p-3 text-xs font-bold text-brand-700">{row.status}</td><td className="p-3"><RecordActions printTitle={`Dispatch Schedule ${row.schedule_no}`} printRecord={{ schedule_no: row.schedule_no, scheduled_date: row.scheduled_date, customer: row.customer?.customer_name, product_code: row.goods?.product?.product_code, product: row.goods?.product?.description, batch: row.goods?.batch?.batch_code, quantity: row.quantity, uom: row.uom?.uom_code, delivery_location: row.delivery_location, vehicle: row.vehicle_no, driver: row.driver_name, remarks: row.remarks, status: row.status }} disabledReason={row.status === 'DISPATCHED' ? 'Completed schedules are controlled dispatch records.' : 'Schedule amendment and cancellation require an audited workflow.'} /></td></tr>)}</tbody></table></div>}</section>
  </div>;
}

export default function DispatchSchedule() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
