import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { AlertCircle, CheckCircle2, Loader2, Plus } from 'lucide-react';
import FactoryGuard from './FactoryGuard'; import FactoryShell from './FactoryShell';
import { createMaster, listSetupData } from './api';

const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-brand-200';
const button='inline-flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40';
type Data={groups:any[];customers:any[];products:any[];operators:any[];machines:any[]};

function SetupBody(){const [data,setData]=useState<Data>({groups:[],customers:[],products:[],operators:[],machines:[]});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{setData(await listSetupData() as Data);}catch(e){setError(e instanceof Error?e.message:'Could not load setup.');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 async function run(action:()=>Promise<unknown>,message:string,form:HTMLFormElement){setBusy(true);setError('');setNotice('');try{await action();form.reset();setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 function customer(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);void run(()=>createMaster('customer',{customer_code:d.get('code'),customer_name:d.get('name'),contact_person:d.get('contact')||null}),'Customer added.',f)}
 function product(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);void run(()=>createMaster('product',{product_code:d.get('code'),description:d.get('name'),product_family:d.get('family'),width_mm:Number(d.get('width')),g_per_meter:Number(d.get('weight'))}),'Product added.',f)}
 function operator(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);void run(()=>createMaster('operator',{operator_code:d.get('code'),full_name:d.get('name')}),'Operator added.',f)}
 function machine(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);void run(()=>createMaster('machine',{legacy_machine_no:Number(d.get('number')),machine_name:d.get('name'),machine_group:d.get('group'),working_width_mm:d.get('width')?Number(d.get('width')):null}),'Verified machine added.',f)}
 const Card=({title,count,children}:{title:string;count:number;children:ReactNode})=><section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex justify-between mb-4"><h2 className="font-bold">{title}</h2><span className="text-xs font-bold text-slate-400">{count} saved</span></div>{children}</section>;
 if(loading)return <div className="py-24 flex justify-center"><Loader2 className="animate-spin text-brand-600"/></div>;
 return <div className="space-y-5"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Phase 1 readiness</p><h1 className="text-2xl font-bold mt-1">Factory master data</h1><p className="text-sm text-slate-500 mt-1">Maintain verified customers, products, operators and machines. Book confirmed demand in Customer Orders.</p></div>{error&&<div className="p-3 bg-red-50 text-red-700 rounded-xl flex gap-2 text-sm"><AlertCircle className="w-4 h-4"/>{error}</div>}{notice&&<div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl flex gap-2 text-sm"><CheckCircle2 className="w-4 h-4"/>{notice}</div>}
 <div className="grid lg:grid-cols-2 gap-4"><Card title="Customers" count={data.customers.length}><form onSubmit={customer} className="grid sm:grid-cols-3 gap-2"><input required name="code" placeholder="Code" className={field}/><input required name="name" placeholder="Customer name" className={field}/><input name="contact" placeholder="Contact person" className={field}/><button disabled={busy} className={`${button} sm:col-span-3`}><Plus className="w-4 h-4"/>Add customer</button></form></Card>
 <Card title="Products" count={data.products.length}><form onSubmit={product} className="grid sm:grid-cols-2 gap-2"><input required name="code" placeholder="Product code" className={field}/><input required name="name" placeholder="Description" className={field}/><select required name="family" className={field}><option value="">Family…</option><option value="J">Jacquard</option><option value="K">Knitted</option><option value="W">Woven</option></select><input required type="number" min="0.01" step="0.01" name="width" placeholder="Width mm" className={field}/><input required type="number" min="0.01" step="0.01" name="weight" placeholder="Grams per meter" className={field}/><button disabled={busy} className={button}><Plus className="w-4 h-4"/>Add product</button></form></Card>
 <Card title="Operators" count={data.operators.length}><form onSubmit={operator} className="grid sm:grid-cols-2 gap-2"><input required name="code" placeholder="Operator code" className={field}/><input required name="name" placeholder="Full name" className={field}/><button disabled={busy} className={`${button} sm:col-span-2`}><Plus className="w-4 h-4"/>Add operator</button></form></Card>
 <Card title="Verified machines" count={data.machines.length}><form onSubmit={machine} className="grid sm:grid-cols-2 gap-2"><input required type="number" min="1" max="17" name="number" placeholder="Legacy MACH NO (1–17)" className={field}/><input required name="name" placeholder="Machine name" className={field}/><select required name="group" className={field}><option value="">Verified group…</option>{data.groups.map(g=><option key={g.machine_group_id} value={g.machine_group_id}>{g.group_name}</option>)}</select><input type="number" min="0.01" step="0.01" name="width" placeholder="Working width mm" className={field}/><button disabled={busy} className={`${button} sm:col-span-2`}><Plus className="w-4 h-4"/>Add verified machine</button></form></Card></div></div>}
export default function FactorySetup(){return <FactoryGuard><FactoryShell><SetupBody/></FactoryShell></FactoryGuard>}
