import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertCircle, CheckCircle2, ChevronRight, Factory, Gauge, Loader2, PackageCheck, Play, RefreshCw, Wrench } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import { assignMachine, completeBatch, listFactoryOptions, listProductionOrders, recordProduction, type FactoryOption, type FactoryOrder } from './api';

const statusLabel: Record<string,string> = { ORDER_CONFIRMED:'Confirmed', PRODUCTION_PLANNED:'Planned', MATERIALS_READY:'Materials ready', MACHINE_ASSIGNED:'Machine assigned', IN_SETUP:'Setup', IN_PRODUCTION:'In production', QC_PENDING:'Awaiting QC' };
const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-500';

function Metric({ label, value, icon: Icon }: {label:string; value:string|number; icon:typeof Factory}) {
  return <div className="bg-white border border-slate-200 rounded-2xl p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><Icon className="w-4 h-4 text-brand-600"/></div><p className="mt-2 text-2xl font-bold">{value}</p></div>;
}

function Select({ label, value, setValue, options }: {label:string;value:string;setValue:(v:string)=>void;options:FactoryOption[]}) {
  return <label className="text-xs font-semibold text-slate-600">{label}<select required value={value} onChange={e=>setValue(e.target.value)} className={`${inputClass} mt-1`}><option value="">Select…</option>{options.map(x=><option key={x.id} value={x.id}>{x.label}{x.meta?` · ${x.meta}`:''}</option>)}</select></label>;
}

function DashboardBody() {
  const [orders,setOrders]=useState<FactoryOrder[]>([]); const [options,setOptions]=useState<Record<string,FactoryOption[]>>({machines:[],operators:[],shifts:[],teams:[]});
  const [selected,setSelected]=useState(''); const [machine,setMachine]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [operator,setOperator]=useState(''); const [shift,setShift]=useState(''); const [team,setTeam]=useState(''); const [strips,setStrips]=useState(''); const [meters,setMeters]=useState(''); const [kg,setKg]=useState(''); const [wastage,setWastage]=useState(''); const [remarks,setRemarks]=useState('');
  const load=useCallback(async()=>{setBusy(true);setError('');try{const [o,opts]=await Promise.all([listProductionOrders(),listFactoryOptions()]);setOrders(o);setOptions(opts);setSelected(s=>s||o[0]?.production_order_id||'');}catch(e){setError(e instanceof Error?e.message:'Could not load Factory Live.');}finally{setBusy(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const current=orders.find(o=>o.production_order_id===selected); const batch=current?.batch?.[0];
  const counts=useMemo(()=>({active:orders.filter(o=>o.status==='IN_PRODUCTION').length,assigned:orders.filter(o=>o.status==='MACHINE_ASSIGNED').length,qc:orders.filter(o=>o.status==='QC_PENDING').length}),[orders]);
  async function act(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await fn();setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}}
  async function submitEntry(e:FormEvent){e.preventDefault();if(!batch)return;await act(()=>recordProduction({batchId:batch.production_batch_id,operatorId:operator,shiftId:shift,teamId:team,strips:Number(strips),meterPerStrip:Number(meters),kgPerStrip:Number(kg),wastage:wastage?Number(wastage):undefined,remarks}),'Production entry posted.');setMeters('');setKg('');setWastage('');setRemarks('');}
  return <div className="space-y-6">
    <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Phase 1</p><h1 className="text-2xl font-bold mt-1">Production control</h1><p className="text-sm text-slate-500 mt-1">Run a confirmed order through one complete factory transaction.</p></div><button onClick={()=>void load()} className="p-2.5 bg-white border border-slate-200 rounded-xl hover:bg-slate-50"><RefreshCw className={`w-4 h-4 ${busy?'animate-spin':''}`}/></button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Orders" value={orders.length} icon={Factory}/><Metric label="Running" value={counts.active} icon={Play}/><Metric label="Assigned" value={counts.assigned} icon={Wrench}/><Metric label="Awaiting QC" value={counts.qc} icon={PackageCheck}/></div>
    {error&&<div className="flex gap-2 p-3 rounded-xl bg-red-50 text-red-700 text-sm"><AlertCircle className="w-4 h-4 mt-0.5"/>{error}</div>}{notice&&<div className="flex gap-2 p-3 rounded-xl bg-emerald-50 text-emerald-700 text-sm"><CheckCircle2 className="w-4 h-4 mt-0.5"/>{notice}</div>}
    <div className="grid lg:grid-cols-[360px_1fr] gap-5">
      <section className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="px-4 py-3 border-b"><h2 className="font-bold">Production orders</h2></div>{busy&&!orders.length?<div className="p-12 flex justify-center"><Loader2 className="animate-spin text-brand-600"/></div>:orders.length===0?<p className="p-8 text-sm text-slate-500 text-center">No production orders yet. Create the first order through Supabase after applying migration 0004.</p>:<div>{orders.map(o=><button key={o.production_order_id} onClick={()=>setSelected(o.production_order_id)} className={`w-full text-left p-4 border-b last:border-0 hover:bg-slate-50 ${selected===o.production_order_id?'bg-brand-50':''}`}><div className="flex justify-between gap-2"><span className="font-mono text-xs font-bold">{o.production_order_no}</span><ChevronRight className="w-4 h-4 text-slate-300"/></div><p className="font-semibold text-sm mt-1">{o.product?.description??'Unlinked product'}</p><span className="inline-block mt-2 text-[10px] font-bold uppercase tracking-wider text-brand-700">{statusLabel[o.status]??o.status}</span></button>)}</div>}</section>
      <section className="bg-white border border-slate-200 rounded-2xl p-5 min-w-0">{!current?<div className="py-20 text-center text-slate-400"><Factory className="w-9 h-9 mx-auto mb-3"/><p>Select a production order.</p></div>:<div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-xs text-slate-500">{current.production_order_no}</p><h2 className="text-xl font-bold">{current.product?.description}</h2></div><span className="h-fit px-3 py-1.5 rounded-full bg-brand-50 text-brand-700 text-xs font-bold">{statusLabel[current.status]??current.status}</span></div>
        {!batch&&<div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-bold text-sm">1. Assign a machine</h3><p className="text-xs text-slate-500 mt-1 mb-3">Creates the first production batch and advances the order.</p><div className="flex gap-2"><select value={machine} onChange={e=>setMachine(e.target.value)} className={inputClass}><option value="">Select machine…</option>{options.machines.map(x=><option key={x.id} value={x.id}>{x.label} · {x.meta}</option>)}</select><button disabled={!machine||busy} onClick={()=>void act(()=>assignMachine(current.production_order_id,machine),'Machine assigned.')} className="px-4 rounded-xl bg-brand-600 text-white text-sm font-bold disabled:opacity-40">Assign</button></div>{options.machines.length===0&&<p className="text-xs text-amber-700 mt-2">Machine master is empty pending NC-28. Add verified machines before assignment.</p>}</div>}
        {batch&&<><div className="grid sm:grid-cols-3 gap-3 bg-slate-50 rounded-2xl p-4"><div><p className="text-[10px] uppercase font-bold text-slate-400">Batch</p><p className="font-mono text-sm font-bold mt-1">{batch.batch_code}</p></div><div><p className="text-[10px] uppercase font-bold text-slate-400">Machine</p><p className="text-sm font-bold mt-1">{batch.machine?.machine_name??'—'}</p></div><div><p className="text-[10px] uppercase font-bold text-slate-400">Output</p><p className="text-sm font-bold mt-1">{Number(batch.actual_quantity).toLocaleString()} m</p></div></div>
          {batch.status!=='COMPLETE'&&<form onSubmit={submitEntry} className="space-y-4"><div><h3 className="font-bold text-sm">2. Record production</h3><p className="text-xs text-slate-500 mt-1">Meter and kg totals are calculated from the per-strip readings.</p></div><div className="grid sm:grid-cols-3 gap-3"><Select label="Operator" value={operator} setValue={setOperator} options={options.operators}/><Select label="Shift" value={shift} setValue={setShift} options={options.shifts}/><Select label="Team" value={team} setValue={setTeam} options={options.teams}/></div><div className="grid sm:grid-cols-3 gap-3">{[['Strips',strips,setStrips],['Meters / strip',meters,setMeters],['Kg / strip',kg,setKg]].map(([l,v,s])=><label key={l as string} className="text-xs font-semibold text-slate-600">{l as string}<input required min="0" step="0.01" type="number" value={v as string} onChange={e=>(s as (x:string)=>void)(e.target.value)} className={`${inputClass} mt-1`}/></label>)}</div><div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Wastage kg<input min="0" step="0.01" type="number" value={wastage} onChange={e=>setWastage(e.target.value)} className={`${inputClass} mt-1`}/></label><label className="text-xs font-semibold text-slate-600">Remarks<input value={remarks} onChange={e=>setRemarks(e.target.value)} className={`${inputClass} mt-1`}/></label></div><div className="flex flex-wrap items-center justify-between gap-3 pt-2"><p className="text-sm"><span className="text-slate-500">Calculated output:</span> <strong>{(Number(strips||0)*Number(meters||0)).toLocaleString()} m</strong></p><button disabled={busy} className="px-5 py-2.5 rounded-xl bg-brand-600 text-white font-bold text-sm disabled:opacity-40">Post entry</button></div></form>}
          {batch.status==='RUNNING'&&<div className="border-t pt-5 flex items-center justify-between gap-3"><div><h3 className="font-bold text-sm">3. Complete batch</h3><p className="text-xs text-slate-500 mt-1">Posts total meter output to the append-only WIP ledger.</p></div><button disabled={busy} onClick={()=>void act(()=>completeBatch(batch.production_batch_id),'Batch completed and stock posted.')} className="px-5 py-2.5 rounded-xl bg-emerald-600 text-white font-bold text-sm disabled:opacity-40">Complete</button></div>}
          {batch.status==='COMPLETE'&&<div className="p-4 rounded-2xl bg-emerald-50 text-emerald-800 flex gap-3"><CheckCircle2 className="w-5 h-5"/><div><p className="font-bold text-sm">Vertical slice complete</p><p className="text-xs mt-1">Output is in the WIP stock ledger and the order is awaiting QC.</p></div></div>}</>}
      </div>}</section>
    </div>
  </div>;
}

export default function FactoryDashboard(){return <FactoryGuard><FactoryShell><DashboardBody/></FactoryShell></FactoryGuard>}
