import { ArrowRight, BarChart3, Boxes, ClipboardCheck, Factory, FileCheck2, FilePlus2, PackageCheck, PackageOpen, Route, Send, Settings2, ShieldCheck, ShoppingCart, Truck, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';

// Static palette tokens ensure Tailwind emits the dynamically selected section colors.
const sectionPalette = 'text-blue-800 bg-blue-50 border-blue-100 text-cyan-800 bg-cyan-50 border-cyan-100 text-amber-800 bg-amber-50 border-amber-100 text-violet-800 bg-violet-50 border-violet-100 text-emerald-800 bg-emerald-50 border-emerald-100';
void sectionPalette;

const flows = [
  { title:'Customers / Sales', tone:'blue', items:[['Design Studio','Create customer design','/studio',FilePlus2,'text-violet-600 bg-violet-100'],['Sample development','Physical approval','/factory/samples',PackageCheck,'text-fuchsia-600 bg-fuchsia-100'],['Quotation / Estimate','Commercial offer','/factory/quotations',FileCheck2,'text-blue-600 bg-blue-100'],['Confirmed order','Demand to factory','/factory/orders',ClipboardCheck,'text-emerald-600 bg-emerald-100']]},
  { title:'Production', tone:'cyan', items:[['Production planning','Plan dates & priority','/factory/planning',ClipboardCheck,'text-indigo-600 bg-indigo-100'],['Production execution','Assign machine & record output','/factory/production',Factory,'text-blue-600 bg-blue-100'],['Quality control','Release or hold','/factory/qc',ShieldCheck,'text-emerald-600 bg-emerald-100']]},
  { title:'Inventory / Store', tone:'amber', items:[['Supplier / PO receipt','Company-owned material','/factory/grn',Truck,'text-amber-600 bg-amber-100'],['Customer custody','Customer-owned conversion','/factory/stock/customer-custody',PackageCheck,'text-fuchsia-600 bg-fuchsia-100'],['Stock register & ledger','Single source of truth','/factory/stock/register',Boxes,'text-orange-600 bg-orange-100'],['Company material issue','Supply production','/factory/material-issues',PackageOpen,'text-rose-600 bg-rose-100']]},
  { title:'Purchasing / Vendors', tone:'violet', items:[['Purchase request','Internal demand','/factory/purchase-requests',ShoppingCart,'text-violet-600 bg-violet-100'],['Approval inbox','Controlled approval','/factory/approvals',FileCheck2,'text-blue-600 bg-blue-100'],['Purchase order','Supplier order','/factory/purchase-orders',ClipboardCheck,'text-amber-600 bg-amber-100'],['Supplier materials','Approved masters','/factory/master/procurement',Boxes,'text-orange-600 bg-orange-100']]},
  { title:'Dispatch', tone:'emerald', items:[['Dispatch schedule','Plan delivery','/factory/dispatch/schedule',Route,'text-sky-600 bg-sky-100'],['Gate pass','Authorize exit','/factory/gate-pass',FileCheck2,'text-indigo-600 bg-indigo-100'],['Company dispatch','Ship company-owned goods','/factory/dispatch',Truck,'text-emerald-600 bg-emerald-100']]},
] as const;

const quick = [
  ['Estimates','/factory/quotations',FileCheck2,'text-violet-600 bg-violet-100'],['QuickBooks sync','/factory/quickbooks',Send,'text-emerald-600 bg-emerald-100'],
] as const;
const reports = [['Production reports','/factory/reports',BarChart3,'text-blue-600 bg-blue-100'],['Stock reports','/factory/reports',Boxes,'text-amber-600 bg-amber-100'],['Quality analytics','/factory/qc/analytics',ShieldCheck,'text-emerald-600 bg-emerald-100'],['Audit log','/factory/audit',ClipboardCheck,'text-violet-600 bg-violet-100']] as const;
const masters = [['Products','/factory/setup',Boxes,'text-amber-600 bg-amber-100'],['BOM / Routings','/factory/master/bom-routings',Route,'text-blue-600 bg-blue-100'],['Suppliers','/factory/master/procurement',Truck,'text-orange-600 bg-orange-100'],['Users & roles','/factory/users',Users,'text-violet-600 bg-violet-100']] as const;

function Flow({flow}:{flow:typeof flows[number]}){return <section className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden"><div className={`px-4 py-2.5 text-center text-xs font-extrabold uppercase tracking-[.12em] text-${flow.tone}-800 bg-${flow.tone}-50 border-b border-${flow.tone}-100`}>{flow.title}</div><div className="p-4 grid grid-cols-2 lg:flex items-stretch gap-2">{flow.items.map(([label,sub,to,Icon,color],i)=><div key={label} className="contents lg:flex lg:flex-1 lg:items-center lg:gap-2"><Link to={to} className="group flex-1 min-h-28 rounded-xl border border-transparent hover:border-slate-200 hover:bg-slate-50 flex flex-col items-center justify-center text-center px-2 transition"><span className={`w-12 h-12 rounded-2xl flex items-center justify-center ${color} group-hover:scale-105 transition-transform`}><Icon className="w-7 h-7"/></span><b className="text-xs mt-2">{label}</b><span className="text-[10px] text-slate-400 mt-0.5">{sub}</span></Link>{i<flow.items.length-1&&<ArrowRight className="hidden lg:block w-5 h-5 text-slate-300 shrink-0"/>}</div>)}</div></section>}
function LinkPanel({title,items}:{title:string;items:readonly (readonly [string,string,typeof Users,string])[]}){return <section className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden"><h2 className="px-4 py-2.5 text-center text-xs font-extrabold uppercase tracking-[.12em] text-blue-800 bg-blue-50 border-b border-blue-100">{title}</h2><div className="p-4 grid grid-cols-2 gap-2">{items.map(([label,to,Icon,color])=><Link key={label} to={to} className="rounded-xl p-3 hover:bg-slate-50 text-center"><span className={`mx-auto w-11 h-11 rounded-2xl flex items-center justify-center ${color}`}><Icon className="w-6 h-6"/></span><p className="text-xs font-semibold mt-2">{label}</p></Link>)}</div></section>}
function Home(){return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold text-blue-600 uppercase tracking-[.18em]">Integrated control</p><h1 className="text-2xl font-bold mt-1">Factory Process Map</h1><p className="text-sm text-slate-500 mt-1">Follow each operating flow from customer design through production, inventory, and dispatch.</p></div><Link to="/factory/overview" className="rounded-xl bg-blue-600 text-white px-4 py-2.5 text-sm font-bold flex gap-2"><BarChart3 className="w-4 h-4"/>Open dashboard</Link></div><div className="grid xl:grid-cols-[minmax(0,1fr)_300px] gap-4"><div className="space-y-4">{flows.map(flow=><Flow key={flow.title} flow={flow}/>)}</div><aside className="space-y-4"><LinkPanel title="Accounting links" items={quick}/><LinkPanel title="Reports" items={reports}/><LinkPanel title="Master data" items={masters}/><Link to="/factory/setup" className="bg-gradient-to-br from-[#073b6f] to-[#0a5592] text-white rounded-xl p-4 shadow-sm flex items-center gap-3"><Settings2 className="w-8 h-8 text-cyan-300"/><div><b className="text-sm">Factory master data</b><p className="text-[10px] text-blue-200">Customers, products, operators and machines</p></div></Link></aside></div></div>}
export default function FactoryHome(){return <FactoryGuard><FactoryShell><Home/></FactoryShell></FactoryGuard>}
