import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {AlertCircle,CheckCircle2,Loader2,Plus,Trash2,Truck} from 'lucide-react';
import FactoryGuard from './FactoryGuard';import FactoryShell from './FactoryShell';import {createReceivingMaster,listReceivingData,postGrn} from './api';
const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-brand-200';const btn='inline-flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40';
type Line={material_id:string;article:string;qty:string;total_weight:string;per_cone_wt:string;supplier_lot_no:string;remarks:string};const blank=():Line=>({material_id:'',article:'',qty:'',total_weight:'',per_cone_wt:'',supplier_lot_no:'',remarks:''});
function Body(){const[data,setData]=useState<any>({suppliers:[],materials:[],grns:[]});const[lines,setLines]=useState<Line[]>([blank()]);const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');
const load=useCallback(async()=>{setLoading(true);try{setData(await listReceivingData());}catch(e){setError(e instanceof Error?e.message:'Could not load receiving.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
async function run(fn:()=>Promise<unknown>,msg:string,form?:HTMLFormElement){setBusy(true);setError('');setNotice('');try{await fn();form?.reset();setNotice(msg);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}}
function addSupplier(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);void run(()=>createReceivingMaster('supplier',{supplier_code:d.get('code'),supplier_name:d.get('name'),supplier_type:d.get('type')||null}),'Supplier added.',f)}
function addMaterial(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);const kg=(data.uoms??[]).find((x:any)=>x.uom_code==='KG');void run(()=>createReceivingMaster('material',{material_code:d.get('code'),material_name:d.get('name'),material_category:d.get('category'),primary_uom:kg?.uom_id}),'Material added.',f)}
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await run(()=>postGrn({supplierId:String(d.get('supplier')),ownership:String(d.get('ownership')),driver:String(d.get('driver')||''),vehicle:String(d.get('vehicle')||''),receivedBy:String(d.get('received')||''),lines:lines.map(x=>({...x,qty:Number(x.qty),total_weight:Number(x.total_weight),per_cone_wt:x.per_cone_wt?Number(x.per_cone_wt):null}))}),'GRN posted to the stock ledger.',f);setLines([blank()])}
function setLine(i:number,key:keyof Line,value:string){setLines(v=>v.map((x,n)=>n===i?{...x,[key]:value}:x))}
if(loading)return <div className="py-24 flex justify-center"><Loader2 className="animate-spin text-brand-600"/></div>;
return <div className="space-y-5"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">IC-F2 replacement</p><h1 className="text-2xl font-bold mt-1">Goods receiving</h1><p className="text-sm text-slate-500 mt-1">One vehicle arrival, multiple material lines, one atomic stock posting.</p></div>{error&&<div className="p-3 bg-red-50 text-red-700 rounded-xl flex gap-2 text-sm"><AlertCircle className="w-4 h-4"/>{error}</div>}{notice&&<div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl flex gap-2 text-sm"><CheckCircle2 className="w-4 h-4"/>{notice}</div>}
<div className="grid lg:grid-cols-2 gap-4"><form onSubmit={addSupplier} className="bg-white rounded-2xl border p-4 grid sm:grid-cols-3 gap-2"><h2 className="font-bold sm:col-span-3">Supplier master</h2><input required name="code" placeholder="Code" className={field}/><input required name="name" placeholder="Supplier name" className={field}/><input name="type" placeholder="Type" className={field}/><button disabled={busy} className={`${btn} sm:col-span-3`}><Plus className="w-4 h-4"/>Add supplier</button></form><form onSubmit={addMaterial} className="bg-white rounded-2xl border p-4 grid sm:grid-cols-3 gap-2"><h2 className="font-bold sm:col-span-3">Material master</h2><input required name="code" placeholder="Code" className={field}/><input required name="name" placeholder="Material name" className={field}/><input required name="category" placeholder="Category" className={field}/><button disabled={busy} className={`${btn} sm:col-span-3`}><Plus className="w-4 h-4"/>Add material</button></form></div>
<form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4"><div className="flex items-center gap-2"><Truck className="w-5 h-5 text-brand-600"/><h2 className="font-bold">Post a GRN</h2></div><div className="grid md:grid-cols-3 gap-2"><select required name="supplier" className={field}><option value="">Supplier…</option>{data.suppliers.map((x:any)=><option key={x.supplier_id} value={x.supplier_id}>{x.supplier_code} · {x.supplier_name}</option>)}</select><select required name="ownership" className={field}><option value="INTERCONVERTERS_OWNED">Interconverters owned</option><option value="TOLL_MANUFACTURING">Toll manufacturing</option><option value="CUSTOMER_OWNED">Customer owned</option><option value="CONSIGNMENT">Consignment</option><option value="OTHER">Other</option></select><input name="received" placeholder="Received by" className={field}/><input name="driver" placeholder="Driver name" className={field}/><input name="vehicle" placeholder="Vehicle number" className={field}/></div><div className="space-y-3">{lines.map((x,i)=><div key={i} className="grid md:grid-cols-7 gap-2 bg-slate-50 rounded-xl p-3"><select required value={x.material_id} onChange={e=>{const m=data.materials.find((z:any)=>z.material_id===e.target.value);setLine(i,'material_id',e.target.value);setLine(i,'article',m?.material_name??'')}} className={field}><option value="">Material…</option>{data.materials.map((m:any)=><option key={m.material_id} value={m.material_id}>{m.material_code} · {m.material_name}</option>)}</select><input required type="number" min="0.01" step="0.01" value={x.qty} onChange={e=>setLine(i,'qty',e.target.value)} placeholder="Qty" className={field}/><input required type="number" min="0.01" step="0.01" value={x.total_weight} onChange={e=>setLine(i,'total_weight',e.target.value)} placeholder="Total kg" className={field}/><input type="number" min="0" step="0.01" value={x.per_cone_wt} onChange={e=>setLine(i,'per_cone_wt',e.target.value)} placeholder="Kg / cone" className={field}/><input value={x.supplier_lot_no} onChange={e=>setLine(i,'supplier_lot_no',e.target.value)} placeholder="Supplier lot" className={field}/><input value={x.remarks} onChange={e=>setLine(i,'remarks',e.target.value)} placeholder="Remarks" className={field}/><button type="button" disabled={lines.length===1} onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))} className="rounded-xl border text-red-500 disabled:opacity-30"><Trash2 className="w-4 h-4 mx-auto"/></button></div>)}</div><div className="flex justify-between"><button type="button" onClick={()=>setLines(v=>[...v,blank()])} className="px-4 py-2.5 rounded-xl border font-bold text-sm"><Plus className="w-4 h-4 inline mr-1"/>Add line</button><button disabled={busy||!data.suppliers.length||!data.materials.length} className={btn}>Post GRN</button></div></form>
<section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Recent receipts</h2>{!data.grns.length?<p className="p-8 text-center text-sm text-slate-400">No GRNs posted yet.</p>:data.grns.map((g:any)=><div key={g.grn_id} className="p-4 border-b last:border-0 flex justify-between gap-3"><div><p className="font-mono text-xs font-bold">{g.grn_no}</p><p className="text-sm text-slate-500 mt-1">{g.supplier?.supplier_name} · {g.ownership}</p></div><span className="text-xs font-bold text-emerald-700">{g.status}</span></div>)}</section></div>}
export default function GoodsReceiving(){return <FactoryGuard><FactoryShell><Body/></FactoryShell></FactoryGuard>}
