import { useEffect, useMemo, useState } from 'react';
import { Boxes, CheckCircle2, Loader2, Printer, TriangleAlert } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { listMaterialPlanning } from './api';

function Body() {
  const [data, setData] = useState<any>({ orders: [], stock: [] }), [loading, setLoading] = useState(true), [error, setError] = useState(''), [onlyShort, setOnlyShort] = useState(false);
  useEffect(() => { listMaterialPlanning().then(setData).catch(e => setError(e instanceof Error ? e.message : 'Could not load material plan.')).finally(() => setLoading(false)); }, []);
  const plan = useMemo(() => {
    const map = new Map<string, any>();
    for (const order of data.orders) for (const bom of order.product?.bom ?? []) { const key = `${bom.material?.material_id}|${bom.uom?.uom_id}`, row = map.get(key) ?? { key, material: bom.material, uom: bom.uom, required: 0, orders: [] }; const quantity = Number(order.target_quantity || 0) * Number(bom.quantity_per_unit || 0) * (1 + Number(bom.wastage_percent || 0) / 100); row.required += quantity; row.orders.push({ no: order.production_order_no, product: order.product?.product_code, qty: quantity }); map.set(key, row); }
    for (const row of map.values()) row.onHand = data.stock.filter((stock: any) => stock.material_id === row.material?.material_id && stock.uom_id === row.uom?.uom_id && ['RAW_MATERIAL', 'CUSTOMER_OWNED_MATERIAL'].includes(stock.stock_category)).reduce((sum: number, stock: any) => sum + Number(stock.quantity || 0), 0);
    return [...map.values()].map(row => ({ ...row, shortage: Math.max(0, row.required - row.onHand), coverage: row.required ? Math.min(100, Math.round(row.onHand / row.required * 100)) : 100 })).sort((a, b) => b.shortage - a.shortage);
  }, [data]);
  const view = onlyShort ? plan.filter(row => row.shortage > 0) : plan, missing = data.orders.filter((order: any) => !(order.product?.bom?.length)).length, totalShort = plan.filter(row => row.shortage > 0).length;
  return <div className="space-y-5">
    <div className="flex justify-between gap-3"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Production readiness</p><h1 className="text-2xl font-bold mt-1">Material Requirements</h1><p className="text-sm text-slate-500 mt-1">Required BOM quantities compared with current raw-material balances.</p></div><button type="button" onClick={() => window.print()} className="h-10 px-3 border rounded-xl bg-white print:hidden" title="Print material plan"><Printer className="w-4 h-4" /></button></div>
    <div className="grid grid-cols-3 gap-3">{[[Boxes, 'Open production orders', data.orders.length], [TriangleAlert, 'Materials short', totalShort], [CheckCircle2, 'Materials covered', plan.length - totalShort]].map(([Icon, label, value]: any) => <div key={label} className="bg-white border rounded-2xl p-4"><Icon className="w-5 h-5 text-brand-600" /><p className="text-xs font-bold text-slate-500 mt-3">{label}</p><p className="text-2xl font-bold">{value}</p></div>)}</div>
    {missing > 0 && <div className="p-3 bg-amber-50 text-amber-800 rounded-xl text-sm"><b>{missing} production order{missing === 1 ? '' : 's'}</b> cannot be planned because the product has no BOM.</div>}{error && <div className="p-4 bg-red-50 text-red-700 rounded-xl">{error}</div>}
    <section className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b flex justify-between items-center"><div><h2 className="font-bold">Consolidated material plan</h2><p className="text-xs text-slate-500">Includes configured wastage allowances</p></div><label className="text-sm flex gap-2 print:hidden"><input type="checkbox" checked={onlyShort} onChange={e => setOnlyShort(e.target.checked)} /> Shortages only</label></div>{loading ? <div className="p-20 flex justify-center"><Loader2 className="animate-spin" /></div> : !view.length ? <p className="p-16 text-center text-slate-400">No material requirements to display.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{['Material', 'Demand sources', 'Required', 'On hand', 'Shortage', 'Coverage', 'Actions'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{view.map(row => <tr key={row.key} className="border-t"><td className="p-3"><b>{row.material?.material_code}</b><p className="text-xs text-slate-500">{row.material?.material_name}</p></td><td className="p-3"><p className="text-xs max-w-sm">{row.orders.map((order: any) => `${order.no} (${order.product})`).join(', ')}</p></td><td className="p-3 font-mono font-bold">{row.required.toLocaleString(undefined, { maximumFractionDigits: 2 })} {row.uom?.uom_code}</td><td className="p-3 font-mono">{row.onHand.toLocaleString()}</td><td className={`p-3 font-mono font-bold ${row.shortage ? 'text-red-600' : 'text-emerald-700'}`}>{row.shortage ? row.shortage.toLocaleString(undefined, { maximumFractionDigits: 2 }) : 'Covered'}</td><td className="p-3 min-w-36"><div className="h-2 bg-slate-100 rounded-full overflow-hidden"><div className={`h-full ${row.coverage >= 100 ? 'bg-emerald-500' : 'bg-red-500'}`} style={{ width: `${row.coverage}%` }} /></div><p className="text-[10px] mt-1">{row.coverage}%</p></td><td className="p-3"><RecordActions printTitle={`Material Requirement ${row.material?.material_code}`} printRecord={{ material_code: row.material?.material_code, material: row.material?.material_name, demand_sources: row.orders, required_quantity: row.required, on_hand_quantity: row.onHand, shortage: row.shortage, coverage_percent: row.coverage, uom: row.uom?.uom_code }} disabledReason="Material requirements are calculated from production orders, BOMs, and the stock ledger." /></td></tr>)}</tbody></table></div>}</section>
  </div>;
}

export default function MaterialPlanning() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
