import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { CalendarDays, CheckCircle2, ClipboardList, Loader2 } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { listProductionPlanning, planProduction } from './api';

const field = 'w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';
const today = () => new Date().toISOString().slice(0, 10);

function Body() {
  const [data, setData] = useState<any>({ orders: [], groups: [] }), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [editing, setEditing] = useState<any>(null);
  const load = useCallback(async () => { setLoading(true); try { setData(await listProductionPlanning()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load production plan.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const stats = useMemo(() => ({ confirmed: data.orders.filter((row: any) => row.status === 'ORDER_CONFIRMED').length, planned: data.orders.filter((row: any) => row.status === 'PRODUCTION_PLANNED').length, urgent: data.orders.filter((row: any) => row.priority === 'URGENT').length }), [data]);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); setBusy(true); setError(''); setNotice('');
    try { await planProduction({ p_order: values.get('order'), p_group: values.get('group'), p_start: values.get('start'), p_end: values.get('end'), p_priority: values.get('priority'), p_notes: values.get('notes') || null }); form.reset(); setEditing(null); setNotice('Production plan saved.'); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not schedule production.'); } finally { setBusy(false); }
  }
  function edit(row: any) { setEditing(row); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  return <div className="space-y-5">
    <div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Production control</p><h1 className="text-2xl font-bold mt-1">Production Planning</h1><p className="text-sm text-slate-500 mt-1">Prioritize confirmed demand and assign its planned manufacturing window.</p></div>
    <div className="grid grid-cols-3 gap-3">{[['Awaiting plan', stats.confirmed], ['Scheduled', stats.planned], ['Urgent', stats.urgent]].map(item => <div key={String(item[0])} className="bg-white border rounded-2xl p-4"><p className="text-xs font-bold text-slate-500">{item[0]}</p><p className="text-2xl font-bold mt-2">{item[1]}</p></div>)}</div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice && <div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4" />{notice}</div>}
    <form key={editing?.production_order_id ?? 'new'} onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4 print:hidden"><div className="flex gap-2"><CalendarDays className="text-brand-600" /><h2 className="font-bold">{editing ? `Update ${editing.production_order_no}` : 'Schedule production order'}</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3"><select required name="order" defaultValue={editing?.production_order_id ?? ''} className={field}><option value="">Production order…</option>{data.orders.filter((row: any) => ['ORDER_CONFIRMED', 'PRODUCTION_PLANNED', 'MATERIALS_PENDING', 'MATERIALS_READY'].includes(row.status)).map((row: any) => <option key={row.production_order_id} value={row.production_order_id}>{row.production_order_no} · {row.product?.description} · {row.order_item?.order?.customer?.customer_name}</option>)}</select><select required name="group" defaultValue={editing?.group?.machine_group_id ?? ''} className={field}><option value="">Machine group…</option>{data.groups.map((row: any) => <option key={row.machine_group_id} value={row.machine_group_id}>{row.group_name}</option>)}</select><select required name="priority" defaultValue={editing?.priority ?? 'NORMAL'} className={field}><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select><input required name="start" type="date" min={editing ? undefined : today()} defaultValue={editing?.planned_start_date ?? ''} className={field} /><input required name="end" type="date" min={editing ? undefined : today()} defaultValue={editing?.planned_end_date ?? ''} className={field} /><input name="notes" defaultValue={editing?.notes ?? ''} placeholder="Planning notes" className={field} /></div><div className="flex gap-2"><button disabled={busy} className="px-5 py-2.5 bg-brand-600 text-white rounded-xl text-sm font-bold disabled:opacity-40">{busy ? <Loader2 className="w-4 h-4 animate-spin" /> : editing ? 'Update production plan' : 'Save production plan'}</button>{editing && <button type="button" onClick={() => setEditing(null)} className="px-5 py-2.5 border rounded-xl text-sm font-bold">Cancel</button>}</div></form>
    <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Planning board</h2>{loading ? <div className="p-16 flex justify-center"><Loader2 className="animate-spin" /></div> : !data.orders.length ? <p className="p-12 text-center text-slate-400"><ClipboardList className="mx-auto mb-2" />No open production orders.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{['Priority', 'Production order', 'Customer / product', 'Target', 'Machine group', 'Window', 'Status', 'Actions'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{data.orders.map((row: any) => <tr key={row.production_order_id} className="border-t"><td className="p-3"><span className={`text-[10px] font-bold px-2 py-1 rounded-full ${row.priority === 'URGENT' ? 'bg-red-100 text-red-700' : row.priority === 'HIGH' ? 'bg-amber-100 text-amber-700' : 'bg-slate-100 text-slate-600'}`}>{row.priority ?? 'NORMAL'}</span></td><td className="p-3 font-mono text-xs font-bold">{row.production_order_no}</td><td className="p-3"><b>{row.product?.product_code} · {row.product?.description}</b><p className="text-xs text-slate-500">{row.order_item?.order?.customer?.customer_name}</p></td><td className="p-3 font-mono">{Number(row.target_quantity || 0).toLocaleString()}</td><td className="p-3">{row.group?.group_name ?? 'Unassigned'}</td><td className="p-3 text-xs">{row.planned_start_date ?? '—'} → {row.planned_end_date ?? '—'}</td><td className="p-3 text-xs font-bold text-brand-700">{row.status}</td><td className="p-3"><RecordActions printTitle={`Production Plan ${row.production_order_no}`} printRecord={{ production_order: row.production_order_no, customer: row.order_item?.order?.customer?.customer_name, product_code: row.product?.product_code, product: row.product?.description, target_quantity: row.target_quantity, priority: row.priority, machine_group: row.group?.group_name, planned_start: row.planned_start_date, planned_end: row.planned_end_date, notes: row.notes, status: row.status }} onEdit={['ORDER_CONFIRMED', 'PRODUCTION_PLANNED', 'MATERIALS_PENDING', 'MATERIALS_READY'].includes(row.status) ? () => edit(row) : undefined} disabledReason="Started or completed production plans are controlled records." /></td></tr>)}</tbody></table></div>}</section>
  </div>;
}

export default function ProductionPlanning() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
