import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { CheckCircle2, Loader2, Plus, ShoppingCart } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { createPurchaseOrder, listPurchaseOrderData } from './api';

const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';
function Body(){
  const[data,setData]=useState<any>({requests:[],suppliers:[],orders:[]});
  const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{setData(await listPurchaseOrderData())}catch(e){setError(e instanceof Error?e.message:'Could not load purchase orders.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);setError('');setNotice('');try{await createPurchaseOrder({requestId:String(d.get('request')),supplierId:String(d.get('supplier')),expectedDate:String(d.get('expected')||''),terms:String(d.get('terms')||''),remarks:String(d.get('remarks')||'')});form.reset();setNotice('Purchase order issued.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not issue purchase order.')}finally{setBusy(false)}}
  return <div className="space-y-5"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Purchasing</p><h1 className="text-2xl font-bold mt-1">Purchase Orders</h1><p className="text-sm text-slate-500 mt-1">Convert approved requests into controlled supplier orders.</p></div>
  {error&&<div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice&&<div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4"/>{notice}</div>}
  <form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4 print:hidden"><h2 className="font-bold">Issue purchase order</h2><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3"><select required name="request" className={field}><option value="">Approved request…</option>{data.requests.map((x:any)=><option key={x.purchase_request_id} value={x.purchase_request_id}>{x.purchase_request_no} · {x.purpose}</option>)}</select><select required name="supplier" className={field}><option value="">Supplier…</option>{data.suppliers.map((x:any)=><option key={x.supplier_id} value={x.supplier_id}>{x.supplier_code} · {x.supplier_name}</option>)}</select><input name="expected" type="date" className={field}/><input name="terms" placeholder="Payment / delivery terms" className={field}/><input name="remarks" placeholder="Remarks" className={field}/></div><button disabled={busy||!data.requests.length||!data.suppliers.length} className="rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-bold text-white flex gap-2 items-center disabled:opacity-40">{busy?<Loader2 className="w-4 h-4 animate-spin"/>:<Plus className="w-4 h-4"/>}Issue PO</button></form>
  <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Purchase order register</h2>{loading?<div className="py-20 flex justify-center"><Loader2 className="animate-spin"/></div>:!data.orders.length?<div className="py-16 text-center text-slate-400"><ShoppingCart className="mx-auto mb-2"/>No purchase orders issued.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">PO</th><th className="p-3">Request</th><th className="p-3">Supplier</th><th className="p-3">Items</th><th className="p-3">Total</th><th className="p-3">Expected</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{data.orders.map((o:any)=>{const total=(o.lines??[]).reduce((n:number,l:any)=>n+Number(l.quantity||0)*Number(l.rate||0),0);return <tr key={o.purchase_order_id} className="border-t"><td className="p-3 font-mono text-xs font-bold">{o.purchase_order_no}</td><td className="p-3 font-mono text-xs">{o.request?.purchase_request_no}</td><td className="p-3">{o.supplier?.supplier_name}</td><td className="p-3">{o.lines?.length??0}</td><td className="p-3 font-bold">{total.toLocaleString()}</td><td className="p-3">{o.expected_date??'—'}</td><td className="p-3"><span className="text-[10px] font-bold px-2 py-1 rounded-full bg-emerald-50 text-emerald-700">{o.status}</span></td><td className="p-3"><RecordActions printTitle={`Purchase Order ${o.purchase_order_no}`} printRecord={{purchase_order:o.purchase_order_no,request:o.request?.purchase_request_no,supplier:o.supplier?.supplier_name,expected_date:o.expected_date,status:o.status,payment_delivery_terms:o.terms,remarks:o.remarks,items:o.lines,total}} disabledReason="Issued purchase orders are controlled records and cannot be deleted."/></td></tr>})}</tbody></table></div>}</section></div>
}
export default function PurchaseOrders(){return <FactoryGuard><FactoryShell><Body/></FactoryShell></FactoryGuard>}
