import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { AlertCircle, CheckCircle2, Loader2, Plus, ShoppingCart } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { createPurchaseRequest, listPurchaseRequests } from './api';

const field = 'w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-brand-200';
const btn = 'rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40';
type Line = { item_description: string; quantity: string; uom: string; rate: string; remarks: string };
const blank = (): Line => ({ item_description: '', quantity: '', uom: 'PCS', rate: '', remarks: '' });

function Body() {
  const [rows, setRows] = useState<any[]>([]), [lines, setLines] = useState<Line[]>([blank()]), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const load = useCallback(async () => { try { setRows(await listPurchaseRequests()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load requests.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  function setLine(index: number, key: keyof Line, value: string) { setLines(current => current.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row)); }
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); setBusy(true); setError(''); setNotice('');
    try { await createPurchaseRequest({ requestedBy: String(values.get('requested')), department: String(values.get('department')), purpose: String(values.get('purpose')), remarks: String(values.get('remarks') || ''), lines: lines.map(line => ({ ...line, quantity: Number(line.quantity), rate: line.rate ? Number(line.rate) : null })) }); form.reset(); setLines([blank()]); setNotice('Purchase request submitted to the Approval Inbox.'); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not create request.'); } finally { setBusy(false); }
  }
  return <div className="space-y-5">
    <div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">IC-FM-04</p><h1 className="text-2xl font-bold mt-1">Purchase requests</h1><p className="text-sm text-slate-500 mt-1">Create requests here. Accountable approval decisions are recorded in the Approval Inbox.</p></div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl flex gap-2 text-sm"><AlertCircle className="w-4 h-4" />{error}</div>}{notice && <div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl flex gap-2 text-sm"><CheckCircle2 className="w-4 h-4" />{notice}</div>}
    <form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-3 print:hidden"><div className="flex gap-2"><ShoppingCart className="w-5 h-5 text-brand-600" /><h2 className="font-bold">New request</h2></div><div className="grid md:grid-cols-4 gap-2"><input required name="requested" placeholder="Requested by" className={field} /><input required name="department" placeholder="Department" className={field} /><input required name="purpose" placeholder="Purpose" className={`${field} md:col-span-2`} /><input name="remarks" placeholder="Remarks" className={`${field} md:col-span-4`} /></div>{lines.map((line, index) => <div key={index} className="grid md:grid-cols-[2fr_.7fr_.7fr_1fr_2fr] gap-2 bg-slate-50 p-3 rounded-xl"><input required value={line.item_description} onChange={e => setLine(index, 'item_description', e.target.value)} placeholder="Item description" className={field} /><input required type="number" min=".01" step=".01" value={line.quantity} onChange={e => setLine(index, 'quantity', e.target.value)} placeholder="Qty" className={field} /><input required value={line.uom} onChange={e => setLine(index, 'uom', e.target.value)} placeholder="UOM" className={field} /><input type="number" min="0" step=".01" value={line.rate} onChange={e => setLine(index, 'rate', e.target.value)} placeholder="Rate" className={field} /><input value={line.remarks} onChange={e => setLine(index, 'remarks', e.target.value)} placeholder="Remarks" className={field} /></div>)}<div className="flex justify-between"><button type="button" onClick={() => setLines(current => [...current, blank()])} className="px-4 py-2 rounded-xl border text-sm font-bold"><Plus className="w-4 h-4 inline" /> Add line</button><button disabled={busy} className={btn}>{busy ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Submit request'}</button></div></form>
    <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Purchase request register</h2>{!rows.length ? <p className="p-8 text-center text-sm text-slate-400">No requests yet.</p> : rows.map(row => { const total = (row.lines ?? []).reduce((sum: number, line: any) => sum + Number(line.quantity || 0) * Number(line.rate || 0), 0); return <div key={row.purchase_request_id} className="p-4 border-b last:border-0 space-y-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><b className="font-mono text-xs">{row.purchase_request_no}</b><p className="text-sm font-semibold mt-1">{row.purpose}</p><p className="text-xs text-slate-500">{row.department} · {row.requested_by} · {row.request_date}</p></div><div className="ml-auto text-right"><span className="text-xs font-bold text-brand-700">{row.status}</span><p className="text-xs text-slate-500 mt-1">{total.toLocaleString(undefined, { maximumFractionDigits: 2 })}</p></div><RecordActions printTitle={`Purchase Request ${row.purchase_request_no}`} printRecord={{ request_no: row.purchase_request_no, date: row.request_date, requested_by: row.requested_by, department: row.department, purpose: row.purpose, remarks: row.remarks, status: row.status, approvals: row.approvals, items: row.lines, estimated_total: total }} disabledReason="Approval actions are available in the controlled Approval Inbox." /></div><div className="grid grid-cols-4 gap-2">{['PREPARED', 'CHECKED', 'PREAPPROVED', 'APPROVED'].map((stage, index) => { const approval = row.approvals?.find((item: any) => item.approval_level === stage); return <div key={stage} className={`p-2 rounded-lg border ${approval ? 'bg-emerald-50' : 'bg-slate-50'}`}><p className="text-[9px] font-bold">{index + 1}. {stage}</p><p className="text-xs mt-1">{approval?.approver_name ?? 'Pending'}</p></div>; })}</div></div>; })}</section>
  </div>;
}

export default function PurchaseRequests() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
