import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Download, FileSpreadsheet, Loader2 } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { listQuickBooksExportData, recordQuickBooksExport } from './api';

const csv = (rows: unknown[][]) => rows.map(row => row.map(value => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\r\n');
function save(name: string, contents: string) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob(['\ufeff', contents], { type: 'text/csv;charset=utf-8' })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }

function Body() {
  const [data, setData] = useState<any>({ customers: [], suppliers: [], products: [], quotes: [], dispatches: [], purchases: [], history: [] }), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setData(await listQuickBooksExportData()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load QuickBooks export data.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function download(kind: string, rows: unknown[][], ids: string[]) { const filename = `IC-${kind}-${new Date().toISOString().slice(0, 10)}.csv`; setBusy(kind); setError(''); try { save(filename, csv(rows)); await recordQuickBooksExport(kind, ids, filename); setNotice(`${filename} downloaded and recorded for reconciliation.`); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create export.'); } finally { setBusy(''); } }
  const exports = [
    { kind: 'MASTER_LISTS', label: 'Customers, vendors & items', count: data.customers.length + data.suppliers.length + data.products.length, ids: [...data.customers.map((row: any) => row.customer_id), ...data.suppliers.map((row: any) => row.supplier_id), ...data.products.map((row: any) => row.product_id)], rows: [['Record Type', 'Name', 'Account No / Item', 'Description', 'Contact', 'Phone'], ...data.customers.map((row: any) => ['CUSTOMER', row.customer_name, row.customer_code, '', row.contact_person, '']), ...data.suppliers.map((row: any) => ['VENDOR', row.supplier_name, row.supplier_code, '', row.contact_person, row.contact_phone]), ...data.products.map((row: any) => ['ITEM', row.description, row.product_code, row.product_family, '', ''])] },
    { kind: 'ESTIMATES', label: 'Studio quotations / estimates', count: data.quotes.length, ids: data.quotes.map((row: any) => row.quotation_id), rows: [['Estimate No', 'Customer', 'Date', 'Valid Until', 'Item', 'Description', 'Quantity', 'Rate', 'Currency', 'Status'], ...data.quotes.map((row: any) => [row.quotation_no, row.customer?.customer_name, new Date().toISOString().slice(0, 10), row.valid_until, row.product?.product_code, row.product?.description, row.quantity, row.unit_rate, row.currency, row.status])] },
    { kind: 'INVOICES', label: 'Dispatched customer invoices', count: data.dispatches.length, ids: data.dispatches.map((row: any) => row.dispatch_id), rows: [['Invoice No', 'Customer', 'Invoice Date', 'Item', 'Description', 'Quantity', 'UOM', 'Dispatch Ref'], ...data.dispatches.map((row: any) => [row.dispatch_no, row.customer?.customer_name, row.dispatch_date, row.goods?.product?.product_code, row.goods?.product?.description, row.quantity, row.uom?.uom_code, row.dispatch_no])] },
    { kind: 'PURCHASE_ORDERS', label: 'Supplier purchase orders', count: data.purchases.length, ids: data.purchases.map((row: any) => row.purchase_order_id), rows: [['PO No', 'Vendor', 'PO Date', 'Expected Date', 'Item Description', 'Quantity', 'UOM', 'Rate', 'Status'], ...data.purchases.flatMap((row: any) => row.lines.map((line: any) => [row.purchase_order_no, row.supplier?.supplier_name, row.order_date, row.expected_date, line.item_description, line.quantity, line.uom_text, line.rate, row.status]))] },
  ];
  return <div className="space-y-5"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Accounting bridge</p><h1 className="text-2xl font-bold mt-1">QuickBooks Enterprise 2021</h1><p className="text-sm text-slate-500 mt-1">Controlled CSV fallback files and export reconciliation history.</p></div><div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-sm text-amber-900"><b>Fallback only:</b> use Web Connector sync normally. Use CSV when the connector is unavailable, then review account mappings in QuickBooks.</div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice && <div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4" />{notice}</div>}
    {loading ? <div className="p-24 flex justify-center"><Loader2 className="animate-spin text-brand-600" /></div> : <div className="grid md:grid-cols-2 gap-4">{exports.map(item => <section key={item.kind} className="bg-white border rounded-2xl p-5"><div className="flex justify-between"><FileSpreadsheet className="w-7 h-7 text-emerald-600" /><span className="text-2xl font-bold">{item.count}</span></div><h2 className="font-bold mt-4">{item.label}</h2><p className="text-xs text-slate-500 mt-1">CSV staging file for QuickBooks review and import.</p><button disabled={busy === item.kind || !item.count} onClick={() => void download(item.kind, item.rows, item.ids)} className="mt-4 w-full rounded-xl bg-brand-600 text-white py-2.5 text-sm font-bold flex justify-center gap-2 disabled:opacity-40">{busy === item.kind ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}Download export</button></section>)}</div>}
    <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="p-4 border-b font-bold">Export history</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{['Exported', 'Type', 'Filename', 'Records', 'Status', 'Actions'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{data.history.map((row: any) => <tr key={row.export_batch_id} className="border-t"><td className="p-3">{new Date(row.exported_at).toLocaleString()}</td><td className="p-3 font-bold">{row.export_kind.replaceAll('_', ' ')}</td><td className="p-3 font-mono text-xs">{row.filename}</td><td className="p-3">{row.record_count}</td><td className="p-3 text-xs font-bold text-emerald-700">{row.status}</td><td className="p-3"><RecordActions printTitle="QuickBooks CSV Export" printRecord={{ exported_at: new Date(row.exported_at).toLocaleString(), export_type: row.export_kind?.replaceAll('_', ' '), filename: row.filename, record_count: row.record_count, status: row.status, exported_by: row.exported_by }} disabledReason="Export reconciliation history is immutable." /></td></tr>)}</tbody></table>{!data.history.length && <p className="p-10 text-center text-slate-400">No exports recorded.</p>}</div></section>
  </div>;
}

export default function QuickBooksExport() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
