import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Download, Loader2, RefreshCw, Send } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import QuickBooksHealth from './QuickBooksHealth';
import RecordActions from './RecordActions';
import { listQuickBooksSync, queueQuickBooksSync } from './api';

function downloadQwc() { const url = `${window.location.origin}/api/qbwc`; const xml = `<?xml version="1.0"?><QBWCXML><AppName>IC Factory Live</AppName><AppID></AppID><AppURL>${url}</AppURL><AppDescription>Interconverters Factory Live synchronization</AppDescription><AppSupport>${window.location.origin}/factory/quickbooks</AppSupport><UserName>interconverters</UserName><OwnerID>{EE4C61AD-4C10-4BF9-9A85-12C5D4773F28}</OwnerID><FileID>{90A44FB7-33D9-4815-AC85-AC86A7E7D1EB}</FileID><QBType>QBFS</QBType><Scheduler><RunEveryNMinutes>15</RunEveryNMinutes></Scheduler><IsReadOnly>false</IsReadOnly></QBWCXML>`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([xml], { type: 'application/xml' })); link.download = 'IC-Factory-Live.qwc'; link.click(); URL.revokeObjectURL(link.href); }

function Body() {
  const [data, setData] = useState<any>({ customers: [], suppliers: [], products: [], quotes: [], dispatches: [], purchases: [], jobs: [] }), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setData(await listQuickBooksSync()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load QuickBooks sync.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const groups = useMemo(() => [{ kind: 'CUSTOMER', label: 'Customers', rows: data.customers, id: 'customer_id' }, { kind: 'VENDOR', label: 'Vendors', rows: data.suppliers, id: 'supplier_id' }, { kind: 'ITEM', label: 'Items', rows: data.products, id: 'product_id' }, { kind: 'ESTIMATE', label: 'Estimates', rows: data.quotes, id: 'quotation_id' }, { kind: 'INVOICE', label: 'Invoices from dispatch', rows: data.dispatches, id: 'dispatch_id' }, { kind: 'PURCHASE_ORDER', label: 'Purchase orders', rows: data.purchases, id: 'purchase_order_id' }], [data]);
  async function queue(group: any, ids = group.rows.map((row: any) => row[group.id])) { setBusy(group.kind); setError(''); try { const count = await queueQuickBooksSync(group.kind, ids); setNotice(`${count} ${group.label.toLowerCase()} queued for QuickBooks.`); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not queue synchronization.'); } finally { setBusy(''); } }
  const counts = data.jobs.reduce((result: any, job: any) => (result[job.status] = (result[job.status] || 0) + 1, result), {});
  return <div className="space-y-5">
    <div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">QuickBooks Web Connector</p><h1 className="text-2xl font-bold mt-1">QuickBooks Enterprise 2021 Sync</h1><p className="text-sm text-slate-500 mt-1">Queue Factory Live records for automatic qbXML synchronization into the desktop company file.</p></div><button onClick={downloadQwc} className="h-fit rounded-xl bg-slate-950 text-white px-4 py-2.5 text-sm font-bold flex gap-2"><Download className="w-4 h-4" />Download .QWC connector</button></div>
    <div className="rounded-2xl border bg-white p-4 text-sm"><b>Setup:</b> Import the .QWC file into QuickBooks Web Connector, enter username <code>interconverters</code>, and use the password configured as <code>QBWC_PASSWORD</code> in Vercel. QuickBooks must approve access to the company file.</div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice && <div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4" />{notice}</div>}
    <div className="grid grid-cols-4 gap-3">{['PENDING', 'PROCESSING', 'SYNCED', 'FAILED'].map(status => <div key={status} className="bg-white border rounded-2xl p-4"><p className="text-xs text-slate-500">{status}</p><p className="text-2xl font-bold">{counts[status] || 0}</p></div>)}</div>
    {loading ? <div className="p-20 flex justify-center"><Loader2 className="animate-spin" /></div> : <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{groups.map(group => <section key={group.kind} className="bg-white border rounded-2xl p-5"><div className="flex justify-between"><h2 className="font-bold">{group.label}</h2><b className="text-2xl">{group.rows.length}</b></div><button disabled={busy === group.kind || !group.rows.length} onClick={() => void queue(group)} className="mt-4 w-full bg-brand-600 text-white rounded-xl py-2.5 text-sm font-bold flex gap-2 justify-center disabled:opacity-40">{busy === group.kind ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}Queue sync</button></section>)}</div>}
    <section className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b flex justify-between"><h2 className="font-bold">Synchronization log</h2><button onClick={() => void load()}><RefreshCw className="w-4 h-4" /></button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs"><tr>{['Created', 'Entity', 'Status', 'QuickBooks ID', 'Result', 'Actions'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{data.jobs.map((job: any) => { const group = groups.find(item => item.kind === job.entity_type); return <tr key={job.sync_job_id} className="border-t"><td className="p-3">{new Date(job.created_at).toLocaleString()}</td><td className="p-3 font-bold">{job.entity_type}</td><td className="p-3">{job.status}</td><td className="p-3 font-mono text-xs">{job.quickbooks_list_id || job.quickbooks_txn_id || '—'}</td><td className="p-3 text-xs text-red-600">{job.last_error || '—'}</td><td className="p-3"><RecordActions printTitle="QuickBooks Sync Event" printRecord={{ created: new Date(job.created_at).toLocaleString(), entity_type: job.entity_type, entity_id: job.entity_id, status: job.status, quickbooks_id: job.quickbooks_list_id || job.quickbooks_txn_id, attempts: job.attempt_count, last_error: job.last_error, request: job.request_payload, response: job.response_payload }} onCorrect={job.status === 'FAILED' && group ? () => void queue(group, [job.entity_id]) : undefined} disabledReason={job.status === 'FAILED' ? 'Use correction to retry this failed record.' : 'Synchronization history is immutable.'} /></td></tr>; })}</tbody></table></div></section>
  </div>;
}

export default function QuickBooksSync() { return <FactoryGuard><FactoryShell><QuickBooksHealth /><Body /></FactoryShell></FactoryGuard>; }
