import { useEffect, useMemo, useState } from 'react';
import { Loader2, Printer } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { listStockRegister } from './api';

const now = () => new Date().toISOString().slice(0, 10);
const field = 'rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm';

function Body() {
  const [rows, setRows] = useState<any[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [item, setItem] = useState(''), [location, setLocation] = useState(''), [customer, setCustomer] = useState(''), [ownership, setOwnership] = useState('');
  const [from, setFrom] = useState(`${new Date().getFullYear()}-01-01`), [to, setTo] = useState(now());
  useEffect(() => { listStockRegister().then(setRows).catch(e => setError(e instanceof Error ? e.message : 'Could not load register.')).finally(() => setLoading(false)); }, []);
  const items = useMemo(() => { const map = new Map<string, string>(); for (const row of rows) { const value = row.product ?? row.material, id = value?.product_id ?? value?.material_id; if (id) map.set(id, `${value.product_code ?? value.material_code} · ${value.description ?? value.material_name}`); } return [...map]; }, [rows]);
  const locations = useMemo(() => { const map = new Map<string, string>(); for (const row of rows) if (row.location?.location_id) map.set(row.location.location_id, row.location.location_name); return [...map]; }, [rows]);
  const customers = useMemo(() => { const map = new Map<string, string>(); for (const row of rows) if (row.customer?.customer_id) map.set(row.customer.customer_id, `${row.customer.customer_code} · ${row.customer.customer_name}`); return [...map]; }, [rows]);
  const selected = useMemo(() => rows.filter(row => { const value = row.product ?? row.material, id = value?.product_id ?? value?.material_id, date = String(row.transaction_date).slice(0, 10); return (!item || id === item) && (!location || row.location?.location_id === location) && (!customer || row.customer?.customer_id === customer) && (!ownership || row.ownership === ownership) && date >= from && date <= to; }), [rows, item, location, customer, ownership, from, to]);
  let running = 0;
  const movements = selected.map(row => ({ ...row, balance: running += Number(row.quantity) }));
  const receipts = selected.reduce((sum, row) => sum + Math.max(0, Number(row.quantity)), 0), issues = selected.reduce((sum, row) => sum + Math.max(0, -Number(row.quantity)), 0);
  return <div className="space-y-5">
    <div className="flex justify-between"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">IC-FM-05</p><h1 className="text-2xl font-bold mt-1">Stock Register</h1><p className="text-sm text-slate-500 mt-1">Receipts, issues, and running balance from the append-only ledger.</p></div><button onClick={() => window.print()} className="h-10 px-3 border rounded-xl bg-white print:hidden" title="Print filtered register"><Printer className="w-4 h-4" /></button></div>
    <section className="bg-white border rounded-2xl p-4 grid md:grid-cols-3 xl:grid-cols-6 gap-3 print:hidden"><select value={item} onChange={e => setItem(e.target.value)} className={field}><option value="">All items</option>{items.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select value={location} onChange={e => setLocation(e.target.value)} className={field}><option value="">All locations</option>{locations.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select value={customer} onChange={e => setCustomer(e.target.value)} className={field}><option value="">All customers</option>{customers.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select value={ownership} onChange={e => setOwnership(e.target.value)} className={field}><option value="">All ownership</option><option value="INTERCONVERTERS_OWNED">Interconverters owned</option><option value="CUSTOMER_OWNED">Customer owned</option><option value="TOLL_MANUFACTURING">Toll manufacturing</option><option value="CONSIGNMENT">Consignment</option><option value="OTHER">Other</option></select><input type="date" value={from} onChange={e => setFrom(e.target.value)} className={field} /><input type="date" value={to} onChange={e => setTo(e.target.value)} className={field} /></section>
    {loading ? <div className="py-24 flex justify-center"><Loader2 className="animate-spin" /></div> : error ? <div className="p-4 bg-red-50 text-red-700 rounded-xl">{error}</div> : <section className="bg-white border rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase"><tr>{['Date', 'Customer', 'Item', 'Movement', 'Reference', 'Receipts', 'Issues', 'Balance', 'UOM', 'Location', 'Remarks', 'Actions'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{movements.map(row => { const value = row.product ?? row.material, quantity = Number(row.quantity); return <tr key={row.stock_ledger_id} className="border-t"><td className="p-3">{new Date(row.transaction_date).toLocaleDateString()}</td><td className="p-3">{row.customer?.customer_name ?? '—'}</td><td className="p-3"><b className="font-mono">{value?.product_code ?? value?.material_code}</b><br /><span className="text-xs text-slate-500">{value?.description ?? value?.material_name}</span></td><td className="p-3">{row.source_transaction_type}</td><td className="p-3">{row.reference_note ?? '—'}</td><td className="p-3 text-emerald-700 font-mono">{quantity > 0 ? quantity.toLocaleString() : '—'}</td><td className="p-3 text-red-600 font-mono">{quantity < 0 ? Math.abs(quantity).toLocaleString() : '—'}</td><td className="p-3 font-mono font-bold">{row.balance.toLocaleString()}</td><td className="p-3">{row.uom?.uom_code}</td><td className="p-3">{row.location?.location_name}</td><td className="p-3 text-xs text-slate-500">{row.stock_category} · {row.ownership}</td><td className="p-3"><RecordActions printTitle="Stock Ledger Entry" printRecord={{ date: new Date(row.transaction_date).toLocaleString(), customer: row.customer?.customer_name, item_code: value?.product_code ?? value?.material_code, item: value?.description ?? value?.material_name, transaction_type: row.source_transaction_type, reference: row.reference_note, quantity: row.quantity, running_balance: row.balance, uom: row.uom?.uom_code, location: row.location?.location_name, category: row.stock_category, ownership: row.ownership }} disabledReason="The stock ledger is append-only and cannot be edited or deleted." /></td></tr>; })}</tbody><tfoot className="bg-brand-50 font-bold"><tr><td colSpan={5} className="p-3 text-right">Totals</td><td className="p-3">{receipts.toLocaleString()}</td><td className="p-3">{issues.toLocaleString()}</td><td className="p-3">{(receipts - issues).toLocaleString()}</td><td colSpan={4} /></tr></tfoot></table>{!selected.length && <p className="p-12 text-center text-slate-400">No matching movements.</p>}</div></section>}
  </div>;
}

export default function StockRegister() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
