import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { CheckCircle2, ClipboardCheck, Loader2 } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import RecordActions from './RecordActions';
import { listStockTakeData, postStockTake } from './api';

const field = 'w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';

function Body() {
  const [data, setData] = useState<any>({ products: [], materials: [], uoms: [], locations: [], counts: [] });
  const [kind, setKind] = useState('material');
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setData(await listStockTakeData()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load stock takes.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); const item = String(values.get('item'));
    setBusy(true); setError(''); setNotice('');
    try { await postStockTake({ p_product: kind === 'product' ? item : null, p_material: kind === 'material' ? item : null, p_uom: values.get('uom'), p_location: values.get('location'), p_ownership: values.get('ownership'), p_category: values.get('category'), p_physical: Number(values.get('physical')), p_counted_by: values.get('counter'), p_reason: values.get('reason') }); form.reset(); setNotice('Physical count posted and variance reconciled.'); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not post stock take.'); } finally { setBusy(false); }
  }
  const items = kind === 'product' ? data.products : data.materials;
  return <div className="space-y-5">
    <div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Inventory control</p><h1 className="text-2xl font-bold mt-1">Stock Take</h1><p className="text-sm text-slate-500 mt-1">Record physical counts and reconcile variances against the append-only ledger.</p></div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm">{error}</div>}{notice && <div className="p-3 bg-emerald-50 text-emerald-700 rounded-xl text-sm flex gap-2"><CheckCircle2 className="w-4 h-4" />{notice}</div>}
    <form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4 print:hidden"><div className="flex gap-2 items-center"><ClipboardCheck className="w-5 h-5 text-brand-600" /><h2 className="font-bold">Post physical count</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3"><select value={kind} onChange={e => setKind(e.target.value)} className={field}><option value="material">Raw material</option><option value="product">Product / finished goods</option></select><select required name="item" className={field}><option value="">Select item…</option>{items.map((row: any) => <option key={row.product_id ?? row.material_id} value={row.product_id ?? row.material_id}>{row.product_code ?? row.material_code} · {row.description ?? row.material_name}</option>)}</select><select required name="location" className={field}><option value="">Location…</option>{data.locations.map((row: any) => <option key={row.location_id} value={row.location_id}>{row.location_name}</option>)}</select><select required name="uom" className={field}><option value="">Unit…</option>{data.uoms.map((row: any) => <option key={row.uom_id} value={row.uom_id}>{row.uom_code}</option>)}</select><select required name="ownership" className={field}><option value="INTERCONVERTERS_OWNED">Interconverters owned</option><option value="CUSTOMER_OWNED">Customer owned</option><option value="TOLL_MANUFACTURING">Toll manufacturing</option><option value="CONSIGNMENT">Consignment</option><option value="OTHER">Other</option></select><select required name="category" className={field}><option value={kind === 'product' ? 'FINISHED_GOODS' : 'RAW_MATERIAL'}>{kind === 'product' ? 'Finished goods' : 'Raw material'}</option><option value="PACKAGING">Packaging</option><option value="WIP">Work in progress</option><option value="SCRAP">Scrap</option><option value="REJECT">Reject</option></select><input required name="physical" type="number" min="0" step=".01" placeholder="Physical quantity" className={field} /><input required name="counter" placeholder="Counted by" className={field} /></div><textarea required name="reason" placeholder="Count reason / authorization reference" className={field} /><button disabled={busy} className="px-5 py-2.5 rounded-xl bg-brand-600 text-white text-sm font-bold disabled:opacity-40">{busy ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Post stock take'}</button></form>
    <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Count register</h2>{loading ? <div className="p-16 flex justify-center"><Loader2 className="animate-spin" /></div> : !data.counts.length ? <p className="p-12 text-center text-slate-400">No physical counts posted.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Count</th><th className="p-3">Item</th><th className="p-3">Location</th><th className="p-3">Book</th><th className="p-3">Physical</th><th className="p-3">Variance</th><th className="p-3">Counted by</th><th className="p-3">Actions</th></tr></thead><tbody>{data.counts.map((row: any) => { const item = row.product ?? row.material; return <tr key={row.stock_take_id} className="border-t"><td className="p-3"><b className="font-mono text-xs">{row.stock_take_no}</b><p className="text-xs text-slate-500">{row.count_date}</p></td><td className="p-3"><b>{item?.product_code ?? item?.material_code}</b><p className="text-xs text-slate-500">{item?.description ?? item?.material_name}</p></td><td className="p-3">{row.location?.location_name}</td><td className="p-3 font-mono">{Number(row.book_quantity).toLocaleString()}</td><td className="p-3 font-mono">{Number(row.physical_quantity).toLocaleString()}</td><td className={`p-3 font-mono font-bold ${Number(row.variance) === 0 ? 'text-emerald-700' : 'text-amber-700'}`}>{Number(row.variance) > 0 ? '+' : ''}{Number(row.variance).toLocaleString()} {row.uom?.uom_code}</td><td className="p-3">{row.counted_by}</td><td className="p-3"><RecordActions printTitle={`Stock Take ${row.stock_take_no}`} printRecord={{ count_no: row.stock_take_no, date: row.count_date, item_code: item?.product_code ?? item?.material_code, item: item?.description ?? item?.material_name, location: row.location?.location_name, book_quantity: row.book_quantity, physical_quantity: row.physical_quantity, variance: row.variance, uom: row.uom?.uom_code, counted_by: row.counted_by, reason: row.reason, status: row.status }} disabledReason="Posted counts and their variance adjustments are immutable audit records." /></td></tr>; })}</tbody></table></div>}</section>
  </div>;
}

export default function StockTake() { return <FactoryGuard><FactoryShell><Body /></FactoryShell></FactoryGuard>; }
