import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Loader2, Plus, Printer, ShieldCheck, Trash2 } from 'lucide-react';
import FactoryGuard from './FactoryGuard';
import FactoryShell from './FactoryShell';
import { listQcData, submitTextileQcInspection } from './api';
import RecordActions from './RecordActions';

const field='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm';
type Defect={defect_type:string;severity:string;quantity:string;disposition:string;notes:string};
const blank=():Defect=>({defect_type:'',severity:'MINOR',quantity:'',disposition:'',notes:''});

function Body(){
  const[data,setData]=useState<any>({batches:[],operators:[],inspections:[]});
  const[defects,setDefects]=useState<Defect[]>([blank()]);
  const[reinspection,setReinspection]=useState('');
  const[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{try{setData(await listQcData())}catch(e){setError(e instanceof Error?e.message:'Could not load QC.')}},[]);
  useEffect(()=>{void load()},[load]);
  function change(i:number,key:keyof Defect,value:string){setDefects(rows=>rows.map((row,n)=>n===i?{...row,[key]:value}:row))}
  async function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const form=e.currentTarget,d=new FormData(form),result=String(d.get('result'));
    const recorded=defects.filter(x=>x.defect_type.trim());
    if(result!=='PASS'&&!recorded.length){setError('Add at least one defect for a hold or rejection.');return}
    setBusy(true);setError('');setNotice('');
    try{await submitTextileQcInspection({p_batch:d.get('batch'),p_inspector:d.get('inspector')||null,p_type:d.get('type'),p_sample_size:Number(d.get('sample')),p_lot:d.get('lot')||'',p_roll:d.get('roll')||'',p_width:d.get('width')?Number(d.get('width')):null,p_pull:d.get('pull')?Number(d.get('pull')):null,p_size:d.get('size')?Number(d.get('size')):null,p_result:result,p_sample_attached:d.get('sample_attached')==='on',p_notes:d.get('notes')||'',p_defects:recorded,p_reinspection_of:d.get('reinspection')||null});form.reset();setDefects([blank()]);setNotice('QC inspection submitted and production status updated.');await load()}
    catch(e){setError(e instanceof Error?e.message:'Could not submit inspection.')}
    finally{setBusy(false)}
  }
  return <div className="space-y-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold text-brand-600 uppercase tracking-[.18em]">Textile quality control</p><h1 className="text-2xl font-bold mt-1">QC Inspection</h1><p className="text-sm text-slate-500 mt-1">Lot and roll inspection with measured values, defects, disposition and reinspection.</p></div><button onClick={()=>window.print()} className="h-10 px-3 border rounded-xl bg-white print:hidden"><Printer className="w-4 h-4"/></button></div>
  {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}{notice&&<div className="p-3 rounded-xl bg-emerald-50 text-emerald-700 text-sm">{notice}</div>}
  <form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4"><h2 className="font-bold flex gap-2"><ShieldCheck className="text-brand-600"/>New inspection</h2>
  <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-2"><select required name="batch" className={field}><option value="">Production batch…</option>{data.batches.map((x:any)=><option key={x.production_batch_id} value={x.production_batch_id}>{x.batch_code} · {x.machine?.machine_name} · {x.order?.product?.description}</option>)}</select><select required name="inspector" className={field}><option value="">Inspector…</option>{data.operators.map((x:any)=><option key={x.operator_id} value={x.operator_id}>{x.full_name}</option>)}</select><select name="type" className={field}><option value="IN_PROCESS">In-process</option><option value="FINAL">Final</option><option value="RANDOM">Random</option></select><input required name="sample" type="number" min="1" placeholder="Sample size" className={field}/><input name="lot" placeholder="Lot / batch number" className={field}/><input name="roll" placeholder="Roll number" className={field}/><select name="reinspection" value={reinspection} onChange={e=>setReinspection(e.target.value)} className={field}><option value="">Original inspection</option>{data.inspections.filter((x:any)=>x.overall_result!=='PASS').map((x:any)=><option key={x.qc_inspection_id} value={x.qc_inspection_id}>{x.report_no??x.qc_inspection_id.slice(0,8)} · {x.batch?.batch_code}</option>)}</select><select required name="result" className={field}><option value="">Overall result…</option><option value="PASS">Pass / release</option><option value="HOLD">Hold</option><option value="REJECT">Reject</option></select><input name="width" type="number" step=".01" placeholder="Measured width (mm)" className={field}/><input name="pull" type="number" step=".01" placeholder="Measured pull ratio" className={field}/><input name="size" type="number" step=".01" placeholder="Measured size (mm)" className={field}/><label className="flex items-center gap-2 px-3 text-sm"><input type="checkbox" name="sample_attached"/>Physical sample attached</label></div>
  <div className="space-y-2"><div className="flex justify-between"><h3 className="font-bold text-sm">Defects</h3><button type="button" onClick={()=>setDefects(v=>[...v,blank()])} className="text-xs font-bold text-brand-600"><Plus className="inline w-4 h-4"/> Add defect</button></div>{defects.map((x,i)=><div key={i} className="grid md:grid-cols-[1.4fr_.8fr_.7fr_1fr_1.4fr_42px] gap-2 bg-slate-50 p-3 rounded-xl"><input value={x.defect_type} onChange={e=>change(i,'defect_type',e.target.value)} placeholder="Defect type" className={field}/><select value={x.severity} onChange={e=>change(i,'severity',e.target.value)} className={field}><option>MINOR</option><option>MAJOR</option><option>CRITICAL</option></select><input value={x.quantity} onChange={e=>change(i,'quantity',e.target.value)} type="number" min="0" step=".01" placeholder="Affected" className={field}/><select value={x.disposition} onChange={e=>change(i,'disposition',e.target.value)} className={field}><option value="">Disposition…</option><option>REWORK</option><option>SCRAP</option><option>CONCESSION</option></select><input value={x.notes} onChange={e=>change(i,'notes',e.target.value)} placeholder="Defect notes" className={field}/><button type="button" disabled={defects.length===1} onClick={()=>setDefects(v=>v.filter((_,n)=>n!==i))} className="border rounded-xl text-red-500 disabled:opacity-30"><Trash2 className="w-4 h-4 mx-auto"/></button></div>)}</div>
  <textarea name="notes" placeholder="Inspection remarks" className={field}/><button disabled={busy||!data.batches.length} className="px-5 py-2.5 bg-brand-600 text-white rounded-xl font-bold text-sm disabled:opacity-40">{busy?<Loader2 className="w-4 h-4 animate-spin"/>:'Submit inspection'}</button></form>
  <section className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-bold p-4 border-b">Inspection register</h2>{!data.inspections.length?<p className="p-10 text-center text-slate-400">No inspections yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs"><tr><th className="p-3">Report</th><th className="p-3">Batch</th><th className="p-3">Machine</th><th className="p-3">Inspector</th><th className="p-3">Result</th><th className="p-3">Date</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{data.inspections.map((x:any)=><tr key={x.qc_inspection_id} className="border-t"><td className="p-3 font-mono text-xs">{x.report_no??'Legacy'}</td><td className="p-3">{x.batch?.batch_code}</td><td className="p-3">{x.batch?.machine?.machine_name}</td><td className="p-3">{x.inspector?.full_name??'—'}</td><td className="p-3 font-bold">{x.overall_result}</td><td className="p-3">{x.inspection_date}</td><td className="p-3"><RecordActions printTitle={`QC Inspection ${x.report_no??''}`} printRecord={{report_no:x.report_no,batch:x.batch?.batch_code,machine:x.batch?.machine?.machine_name,inspector:x.inspector?.full_name,inspection_date:x.inspection_date,inspection_type:x.inspection_type,lot_batch_no:x.lot_batch_no,roll_no:x.roll_no,measured_width_mm:x.measured_width_mm,measured_pull_ratio:x.measured_pull_ratio,measured_size_mm:x.measured_size_mm,result:x.overall_result,defects:x.defects,notes:x.notes}} onCorrect={x.overall_result==='PASS'?undefined:()=>{setReinspection(x.qc_inspection_id);window.scrollTo({top:0,behavior:'smooth'})}} disabledReason="QC records are immutable; use reinspection for corrections."/></td></tr>)}</tbody></table></div>}</section></div>
}
export default function TextileQualityControl(){return <FactoryGuard><FactoryShell><Body/></FactoryShell></FactoryGuard>}
