-- Machine downtime and maintenance lifecycle.
create sequence if not exists public.seq_maintenance_event start 1;
create table public.maintenance_events(maintenance_event_id uuid primary key default gen_random_uuid(),event_no text not null unique,machine_id uuid not null references public.machines(machine_id),reported_at timestamptz not null default now(),reported_by text not null,category text not null,severity text not null check(severity in('LOW','MEDIUM','HIGH','CRITICAL')),description text not null,status text not null default'OPEN' check(status in('OPEN','IN_PROGRESS','RESOLVED','CANCELLED')),assigned_to text,resolved_at timestamptz,resolved_by text,resolution text,downtime_minutes int generated always as(case when resolved_at is null then null else greatest(0,extract(epoch from(resolved_at-reported_at))/60)::int end)stored,created_at timestamptz not null default now(),created_by text not null default'system',updated_at timestamptz not null default now(),updated_by text);
create or replace function public.report_machine_downtime(p_machine uuid,p_reported_by text,p_category text,p_severity text,p_description text,p_assigned_to text default null)returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;v_no text;begin if not has_factory_role(auth.uid(),array['admin','production_manager','supervisor','operator','maintenance'])then raise exception'not authorized';end if;if nullif(trim(p_description),'')is null then raise exception'description is required';end if;v_no:='ME-'||to_char(current_date,'YYYYMMDD')||'-'||lpad(nextval('seq_maintenance_event')::text,4,'0');insert into maintenance_events(event_no,machine_id,reported_by,category,severity,description,assigned_to,created_by)values(v_no,p_machine,p_reported_by,p_category,p_severity,p_description,p_assigned_to,auth.uid()::text)returning maintenance_event_id into v_id;update machines set active_status=false,updated_at=now(),updated_by=auth.uid()::text where machine_id=p_machine;insert into audit_log(user_id,action,entity_type,entity_id,new_value)values(auth.uid(),'Machine Downtime Reported','maintenance_events',v_id,jsonb_build_object('event_no',v_no,'machine_id',p_machine,'severity',p_severity));return v_id;end$$;
create or replace function public.resolve_machine_maintenance(p_event uuid,p_resolved_by text,p_resolution text)returns uuid language plpgsql security definer set search_path=public as $$declare v_machine uuid;begin if not has_factory_role(auth.uid(),array['admin','maintenance'])then raise exception'not authorized';end if;if nullif(trim(p_resolution),'')is null then raise exception'resolution is required';end if;update maintenance_events set status='RESOLVED',resolved_at=now(),resolved_by=p_resolved_by,resolution=p_resolution,updated_at=now(),updated_by=auth.uid()::text where maintenance_event_id=p_event and status in('OPEN','IN_PROGRESS')returning machine_id into v_machine;if v_machine is null then raise exception'event is not open';end if;if not exists(select 1 from maintenance_events where machine_id=v_machine and status in('OPEN','IN_PROGRESS'))then update machines set active_status=true,updated_at=now(),updated_by=auth.uid()::text where machine_id=v_machine;end if;insert into audit_log(user_id,action,entity_type,entity_id,new_value)values(auth.uid(),'Machine Maintenance Resolved','maintenance_events',p_event,jsonb_build_object('machine_id',v_machine,'resolved_by',p_resolved_by));return p_event;end$$;
alter table public.maintenance_events enable row level security;
create policy factory_read_maintenance on public.maintenance_events for select using(has_factory_role(auth.uid(),array['admin','production_manager','supervisor','operator','maintenance','viewer']));
grant execute on function public.report_machine_downtime(uuid,text,text,text,text,text)to authenticated;
grant execute on function public.resolve_machine_maintenance(uuid,text,text)to authenticated;
