-- Factory technical construction and internal costing gate before a commercial quotation.
create table public.quote_costings(quote_costing_id uuid primary key default gen_random_uuid(),rfq_id uuid not null unique references public.rfqs(id)on delete cascade,currency text not null default'PKR',overhead_percent numeric not null default 0 check(overhead_percent>=0),status text not null default'DRAFT'check(status in('DRAFT','FINAL')),notes text,created_at timestamptz not null default now(),created_by text not null default'system',updated_at timestamptz not null default now(),updated_by text);
create table public.quote_costing_lines(quote_costing_line_id uuid primary key default gen_random_uuid(),quote_costing_id uuid not null references public.quote_costings(quote_costing_id)on delete cascade,line_no int not null,cost_type text not null check(cost_type in('MATERIAL','LABOR','MACHINE','OUTSIDE_SERVICE','PACKAGING','OTHER')),description text not null,quantity numeric not null check(quantity>0),uom text not null,unit_cost numeric not null check(unit_cost>=0),unique(quote_costing_id,line_no));
alter table public.quote_costings enable row level security;alter table public.quote_costing_lines enable row level security;
create policy factory_read_quote_costings on public.quote_costings for select using(has_factory_role(auth.uid(),array['admin','production_manager','accounts','viewer']));
create policy factory_read_quote_costing_lines on public.quote_costing_lines for select using(exists(select 1 from quote_costings c where c.quote_costing_id=quote_costing_lines.quote_costing_id and has_factory_role(auth.uid(),array['admin','production_manager','accounts','viewer'])));

create or replace function public.list_factory_quote_preparation_sources()returns table(rfq_id uuid,design_project_id uuid,design_code text,design_name text,family text,revision_no int,contact_name text,company text,email text,quantity text,quantity_unit text,target_price text,target_date date)language sql stable security definer set search_path=public as $$select r.id,p.id,p.design_code,p.name,p.family::text,p.current_revision,r.contact_name,r.company,r.email,r.quantity,r.quantity_unit,r.target_price,r.target_date from rfqs r join design_projects p on p.id=r.project_id where has_factory_role(auth.uid(),array['admin','production_manager','accounts','viewer'])and r.kind in('quote','sample')and r.status in('Submitted','Under Review','Sample Development','Sample Approved')and not exists(select 1 from factory_quotations q where q.rfq_id=r.id)order by r.created_at$$;

create or replace function public.save_quote_preparation(p_rfq uuid,p_details jsonb,p_currency text,p_overhead_percent numeric,p_status text,p_notes text,p_lines jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare v_project uuid;v_cost uuid;v_line jsonb;v_no int:=0;v_subtotal numeric:=0;begin if not has_factory_role(auth.uid(),array['admin','production_manager','accounts'])then raise exception'not authorized';end if;if p_status not in('DRAFT','FINAL')or p_overhead_percent<0 then raise exception'invalid preparation status or overhead';end if;if jsonb_typeof(p_lines)<>'array'or jsonb_array_length(p_lines)=0 then raise exception'at least one cost line is required';end if;select project_id into v_project from rfqs where id=p_rfq and kind in('quote','sample');if not found then raise exception'request not found';end if;insert into production_specs(project_id,details,status,updated_by)values(v_project,p_details,case when p_status='FINAL'then'approved'else'draft'end,auth.uid()::text)on conflict(project_id)do update set details=excluded.details,status=excluded.status,updated_at=now(),updated_by=auth.uid()::text;insert into quote_costings(rfq_id,currency,overhead_percent,status,notes,created_by,updated_by)values(p_rfq,upper(coalesce(nullif(trim(p_currency),''),'PKR')),p_overhead_percent,p_status,nullif(trim(p_notes),''),auth.uid()::text,auth.uid()::text)on conflict(rfq_id)do update set currency=excluded.currency,overhead_percent=excluded.overhead_percent,status=excluded.status,notes=excluded.notes,updated_at=now(),updated_by=auth.uid()::text returning quote_costing_id into v_cost;delete from quote_costing_lines where quote_costing_id=v_cost;for v_line in select value from jsonb_array_elements(p_lines)loop v_no:=v_no+1;if nullif(trim(v_line->>'description'),'')is null or coalesce((v_line->>'quantity')::numeric,0)<=0 or coalesce((v_line->>'unit_cost')::numeric,-1)<0 then raise exception'invalid cost line %',v_no;end if;insert into quote_costing_lines(quote_costing_id,line_no,cost_type,description,quantity,uom,unit_cost)values(v_cost,v_no,v_line->>'cost_type',trim(v_line->>'description'),(v_line->>'quantity')::numeric,upper(trim(v_line->>'uom')),(v_line->>'unit_cost')::numeric);v_subtotal:=v_subtotal+(v_line->>'quantity')::numeric*(v_line->>'unit_cost')::numeric;end loop;update rfqs set status=case when p_status='FINAL'then'Under Review'else status end where id=p_rfq;insert into audit_log(user_id,action,entity_type,entity_id,new_value)values(auth.uid(),'Quotation Preparation Saved','quote_costings',v_cost,jsonb_build_object('status',p_status,'subtotal',v_subtotal,'total',v_subtotal*(1+p_overhead_percent/100)));return v_cost;end$$;

create or replace function public.list_factory_quote_sources()returns table(rfq_id uuid,design_project_id uuid,design_code text,design_name text,family text,revision_no int,contact_name text,company text,email text,quantity text,quantity_unit text,target_price text,target_date date)language sql stable security definer set search_path=public as $$select r.id,p.id,p.design_code,p.name,p.family::text,p.current_revision,r.contact_name,r.company,r.email,r.quantity,r.quantity_unit,r.target_price,r.target_date from rfqs r join design_projects p on p.id=r.project_id join production_specs ps on ps.project_id=p.id and ps.status='approved'join quote_costings c on c.rfq_id=r.id and c.status='FINAL'where has_factory_role(auth.uid(),array['admin','production_manager','accounts','viewer'])and r.kind in('quote','sample')and r.status='Under Review'and not exists(select 1 from factory_quotations q where q.rfq_id=r.id)order by r.created_at$$;
revoke all on function public.list_factory_quote_preparation_sources()from public;revoke all on function public.save_quote_preparation(uuid,jsonb,text,numeric,text,text,jsonb)from public;grant execute on function public.list_factory_quote_preparation_sources()to authenticated;grant execute on function public.save_quote_preparation(uuid,jsonb,text,numeric,text,text,jsonb)to authenticated;
